// questions-18.js - Preguntas de "Secretos íntimos (+18)" con nivel, tema y formato.
//   Formatos: exp   -> ✅ Lo he hecho / 😏 No, pero me gustaría / 🙅 No y no me interesa
//             conf  -> 🙋 Me ha pasado / 🙅 Nunca (cosas que nadie "quiere" hacer)
//             gusto -> opciones propias de cada pregunta
//   El nivel sube según qué tan explícito es el acto, no según el lugar.

export const NIVELES_18 = [
  { lvl: 1, icon: "1🌶️", title: "Coqueto", desc: "Sin mencionar sexo: besos, coqueteo, apps y celos." },
  { lvl: 2, icon: "2🌶️", title: "Atrevido", desc: "Se habla de sexo, pero sin detalles." },
  { lvl: 3, icon: "3🌶️", title: "Picante", desc: "Situaciones de riesgo y juegos en pareja." },
  { lvl: 4, icon: "4🌶️", title: "Muy picante", desc: "Más de dos personas y prácticas intensas.", warn: true },
  { lvl: 5, icon: "5🌶️", title: "Sin filtro", desc: "Prácticas específicas, dichas sin rodeos.", warn: true },
];

export const TEMAS_18 = [
  { tema: "coqueteo", icon: "💋", title: "Coqueteo y besos" },
  { tema: "apps", icon: "📱", title: "Apps, chats y ex" },
  { tema: "experiencias", icon: "🔥", title: "Experiencias" },
  { tema: "juguetes", icon: "🧸", title: "Juguetes y accesorios" },
  { tema: "fantasias", icon: "💭", title: "Fantasías y gustos" },
  { tema: "secretos", icon: "🤫", title: "Secretos e infidelidad" },
  { tema: "verguenza", icon: "😳", title: "Momentos vergonzosos" },
];

const RAW = {
  coqueteo: [
    [1, "exp", "Besar a alguien que acababa de conocer esa misma noche"],
    [1, "exp", "Dar yo el primer beso, sin esperar a que la otra persona se lanzara"],
    [1, "exp", "Besar a alguien bajo la lluvia"],
    [1, "exp", "Besar a alguien en una fiesta y no volver a verle nunca más"],
    [1, "exp", "Coquetear con alguien para conseguir algo (un trago gratis, un descuento, un favor)"],
    [1, "exp", "Declararle mis sentimientos a alguien por mensaje"],
    [1, "exp", "Invitar yo a salir a alguien que me gustaba mucho"],
    [1, "exp", "Tener una cita a ciegas"],
    [1, "exp", "Enamorarme de alguien a primera vista"],
    [1, "exp", "Besar a un amigo o amiga \"solo para probar\""],
    [1, "exp", "Terminar besando a alguien por un juego de verdad o reto"],
    [1, "exp", "Coquetear con alguien sin hablar bien su idioma"],
    [1, "exp", "Mandarle un regalo o una carta anónima a alguien que me gustaba"],
    [1, "exp", "Besar a alguien en un concierto o festival"],
    [1, "exp", "Besar a alguien en el primer minuto de Año Nuevo"],
    [1, "exp", "Cantarle o dedicarle una canción a alguien para conquistarle"],
    [1, "exp", "Tener una cita en la que nos quedamos conversando hasta el amanecer"],
    [1, "conf", "Besar a alguien y al día siguiente no acordarme de su nombre"],
    [1, "conf", "Tener un crush con el pololo o polola de un amigo o amiga"],
    [1, "conf", "Besar a alguien solo para poner celosa a otra persona"],
    [1, "conf", "Que me rechacen un beso"],
    [1, "conf", "Enamorarme de un profesor, profesora o jefe"],
    [1, "conf", "Tener un crush secreto con alguien de este grupo"],
    [1, "conf", "Darme cuenta a mitad de la cita de que no me gustaba y fingir hasta el final"],
    [1, "conf", "Inventar una emergencia para escapar de una cita"],
    [1, "conf", "Chocar los dientes en un beso"],
    [1, "conf", "Enamorarme de alguien que nunca supo que me gustaba"],
    [1, "gusto", "¿Qué te conquista primero?", ["Una buena conversación", "Que me haga reír", "Su físico", "Su seguridad", "Que me escuche"]],
    [1, "gusto", "¿Quién debería dar el primer paso?", ["Yo", "La otra persona", "Da lo mismo"]],
    [1, "gusto", "¿Tu beso favorito?", ["Tierno y lento", "Apasionado", "En el cuello", "Robado por sorpresa"]],
    [1, "gusto", "¿Primera cita ideal?", ["Cena", "Unos tragos", "Algo al aire libre", "Cine", "Cocinar en casa"]],
    [2, "exp", "Besar a más de 3 personas en una misma noche"],
    [2, "exp", "Besarme con alguien en una disco sin saber ni su nombre"],
    [2, "exp", "Besar a alguien de mi mismo sexo"],
    [2, "exp", "Besar a dos personas a la vez"],
    [2, "exp", "Besarme con alguien del trabajo o la universidad"],
    [2, "exp", "Dejar un chupón a propósito"],
    [2, "exp", "Morder o que me muerdan el labio al besar"],
    [2, "exp", "Coquetear con alguien estando en pareja, sin llegar a más"],
    [2, "conf", "Besar a alguien sabiendo que tenía pareja"],
    [2, "conf", "Besar a alguien que me caía pésimo, por pura tensión"],
    [2, "conf", "Besar al ex de un amigo o amiga"],
    [2, "conf", "Haber besado a más de 20 personas en mi vida"],
    [2, "gusto", "¿Dónde te gusta más que te besen?", ["Labios", "Cuello", "Orejas", "Espalda", "Manos"]],
    [3, "exp", "Hacerle un baile sensual a alguien en una disco"],
    [3, "exp", "Besar a alguien en el cine hasta perderme la película"],
    [3, "exp", "Pasar una noche entera de besos con alguien y al día siguiente hacer como si nada"],
    [3, "exp", "Besar a alguien en público de forma tan intensa que la gente se quedara mirando"],
    [2, "exp", "Besar a alguien en el ascensor o en la escalera de un edificio"],
    [2, "exp", "Sacar a bailar a alguien en una disco para dar el primer paso"],
    [2, "exp", "Besar a alguien que conocí ese mismo día en un viaje"],
    [2, "conf", "Besar a alguien y enterarme después de que era pariente de un amigo"],
    [2, "gusto", "¿Beso en la primera cita?", ["Obvio", "Solo si hay química", "Mejor esperar"]],
    [3, "exp", "Besar a alguien pasándonos un hielo o un trago de boca a boca"],
    [3, "exp", "Besarle el cuello a alguien en público hasta sacarle un suspiro"],
    [3, "exp", "Hacer un juego de besos con los ojos vendados"],
    [3, "exp", "Besar a alguien de mi mismo sexo delante de mis amigos"],
    [3, "exp", "Besarme con dos personas distintas en una misma fiesta, una delante de la otra"],
    [3, "conf", "Besar a alguien de este grupo o del círculo cercano"],
    [4, "exp", "Besar a los dos integrantes de una pareja en la misma noche"],
  ],

  apps: [
    [1, "exp", "Crear un perfil falso para espiar a alguien"],
    [1, "exp", "Usar Tinder, Bumble u otra app de citas"],
    [1, "exp", "Tener una cita con alguien que conocí por una app"],
    [1, "exp", "Pedirle el Instagram a alguien en persona"],
    [1, "exp", "Terminar una relación por WhatsApp"],
    [1, "exp", "Tener una relación a distancia por videollamada"],
    [1, "conf", "Stalkear a mi ex en redes a las 3 de la mañana"],
    [1, "conf", "Hacerle ghosting a alguien con quien estaba saliendo"],
    [1, "conf", "Que me hagan ghosting"],
    [1, "conf", "Darle \"me gusta\" por error a una foto antigua de alguien que estaba stalkeando"],
    [1, "conf", "Mandarle la captura del chat a la misma persona de la que estaba hablando"],
    [1, "conf", "Volver con un ex que había jurado no volver a ver"],
    [1, "conf", "Usar apps de citas teniendo pareja"],
    [1, "conf", "Revisar a qué hora se conectó mi pareja o mi crush"],
    [1, "conf", "Borrar un chat comprometedor antes de ver a mi pareja"],
    [1, "conf", "Escribirle a un ex estando con copete"],
    [1, "conf", "Llegar a una cita de app y ver que las fotos eran de hace años"],
    [1, "conf", "Mentir sobre mi edad o altura en una app de citas"],
    [1, "conf", "Subir una historia solo para que la viera una persona"],
    [1, "conf", "Silenciar o archivar a alguien para no ver lo feliz que estaba con otra persona"],
    [1, "gusto", "¿Qué es peor cuando te gusta alguien?", ["Que te dejen en visto", "Que te contesten solo \"jaja\"", "Que te contesten 3 días después"]],
    [1, "gusto", "¿Dónde es mejor conocer a alguien?", ["En una app", "Por amigos", "En un carrete", "En el trabajo o la U"]],
    [1, "gusto", "¿Seguir a tu ex en redes?", ["Sí, sin drama", "Silenciado", "Bloqueado para siempre"]],
    [2, "exp", "Mandar una foto sugerente (sin llegar a desnudo)"],
    [2, "exp", "Hacer sexting con alguien"],
    [2, "exp", "Mandar mensajes subidos de tono estando en una reunión o en el trabajo"],
    [2, "exp", "Tener sexo con alguien de una app la misma noche que nos conocimos"],
    [2, "exp", "Tener un \"amigo con derechos\" que conocí por una app"],
    [2, "exp", "Hacer una videollamada subida de tono"],
    [2, "exp", "Mandar una indirecta caliente por historias de mejores amigos"],
    [2, "conf", "Mandar un mensaje caliente a la persona equivocada"],
    [2, "conf", "Mandar audios calientes con copete y arrepentirme al día siguiente"],
    [2, "conf", "Acostarme con un ex \"una última vez\""],
    [2, "conf", "Seguir acostándome con un ex mientras empezaba a salir con otra persona"],
    [2, "conf", "Buscar algo de una noche en una app y no volver a contestar"],
    [2, "gusto", "¿Qué te parece mandar nudes?", ["Normal, con confianza", "Solo con mi pareja", "Nunca, ni loco/a"]],
    [3, "exp", "Mandar un desnudo (nude)"],
    [3, "exp", "Tener sexo por videollamada con alguien que no conocía en persona"],
    [3, "exp", "Grabar un video íntimo con mi pareja"],
    [3, "exp", "Usar una app de citas solo para encuentros sexuales"],
    [3, "exp", "Pedirle un nude a alguien"],
    [3, "conf", "Mandar un nude por error a la persona equivocada"],
    [3, "conf", "Guardar fotos o videos íntimos en una carpeta oculta del celular"],
    [3, "conf", "Hacer sexting con otra persona estando en pareja"],
    [3, "gusto", "¿Nudes con cara o sin cara?", ["Con cara", "Sin cara", "No mando"]],
    [4, "exp", "Buscar en una app a alguien para hacer un trío"],
    [4, "exp", "Tener una cuenta de OnlyFans o vender contenido íntimo"],
    [4, "exp", "Pagar por contenido íntimo de alguien (OnlyFans u otro)"],
    [4, "exp", "Tener sexo por videollamada con más de una persona"],
    [1, "exp", "Hacer match con alguien conocido del trabajo o la universidad"],
    [1, "conf", "Hacer match con un ex en una app de citas"],
    [1, "conf", "Sacarle captura al perfil de alguien para mostrárselo a mis amigos"],
    [1, "gusto", "¿Qué foto de perfil funciona mejor?", ["Selfie", "Con mascota", "Viajando", "Con amigos", "Haciendo deporte"]],
    [2, "exp", "Cambiarle el nombre a un contacto para esconder con quién hablaba"],
    [2, "exp", "Coquetear por mensaje privado de Instagram con alguien que no conocía"],
    [2, "conf", "Quedarme dormido/a en plena conversación caliente"],
    [2, "conf", "Reaccionar sin querer a una historia de mi ex"],
    [3, "exp", "Mandar un video subido de tono"],
    [3, "exp", "Hacer sexting con dos personas en la misma semana"],
    [3, "exp", "Hacer una videollamada desnudo/a"],
    [3, "conf", "Que alguien viera por accidente una conversación caliente en mi celular"],
    [4, "exp", "Grabar un video íntimo con alguien que no era mi pareja"],
    [4, "exp", "Hacer una videollamada caliente con mi pareja y otra persona"],
  ],

  experiencias: [
    [1, "exp", "Tener un romance de verano o de vacaciones"],
    [1, "exp", "Hacer un viaje romántico improvisado con alguien que recién conocía"],
    [1, "exp", "Salir con alguien 10 años mayor que yo"],
    [1, "exp", "Salir con alguien 10 años menor que yo"],
    [1, "exp", "Tener dos citas con personas distintas el mismo día"],
    [1, "exp", "Salir con dos personas al mismo tiempo sin que lo supieran"],
    [1, "exp", "Enamorarme de un amigo o amiga de toda la vida"],
    [1, "exp", "Tener una relación a distancia"],
    [1, "exp", "Pololear con alguien del trabajo o la universidad"],
    [2, "exp", "Tener un one night stand (sexo de una sola noche)"],
    [2, "exp", "Irme de la casa de alguien antes de que amaneciera"],
    [2, "exp", "Ir a un motel"],
    [2, "exp", "Ir a un motel temático"],
    [2, "exp", "Tener sexo en la primera cita"],
    [2, "exp", "Tener un \"amigo con derechos\""],
    [2, "exp", "Tener sexo con alguien del trabajo o la universidad"],
    [2, "exp", "Tener sexo con un ex después de terminar"],
    [2, "exp", "Tener sexo en el auto"],
    [2, "exp", "Tener sexo en la casa de mis papás o de mis suegros"],
    [2, "exp", "Tener sexo en la ducha"],
    [2, "exp", "Tener sexo en la playa"],
    [2, "exp", "Tener sexo en una carpa en un camping"],
    [2, "exp", "Tener sexo con alguien de mi mismo sexo"],
    [2, "exp", "Tener sexo con alguien mucho mayor que yo"],
    [2, "exp", "Tener sexo con alguien que conocí en un viaje"],
    [2, "exp", "Tener sexo en un jacuzzi o piscina"],
    [2, "exp", "Hacer una escapada de fin de semana solo para estar en la cama"],
    [2, "exp", "Tener sexo mañanero con resaca"],
    [2, "exp", "Tener sexo más de 3 veces en un mismo día"],
    [2, "exp", "Tener sexo de reconciliación después de una pelea"],
    [2, "exp", "Tener sexo en una despedida de soltero o soltera"],
    [2, "exp", "Tener sexo con alguien de otro país"],
    [2, "conf", "Haber tenido sexo con más de 10 personas en mi vida"],
    [2, "conf", "Tener sexo con alguien solo porque estaba aburrido/a o me sentía solo/a"],
    [2, "conf", "Tener sexo con alguien cuyo nombre ya no recuerdo"],
    [2, "conf", "Tener sexo con alguien que me caía mal"],
    [2, "gusto", "¿A qué hora es mejor?", ["En la mañana", "En la tarde", "En la noche", "A cualquier hora"]],
    [2, "gusto", "¿Qué es mejor?", ["Sexo de reconciliación", "Sexo de cumpleaños", "Sexo de vacaciones"]],
    [2, "gusto", "¿Cuánto te duró tu relación más larga?", ["Menos de 1 año", "De 1 a 3 años", "Más de 3 años", "Nunca he tenido pareja"]],
    [3, "exp", "Tener sexo en un lugar público con riesgo de que nos vieran"],
    [3, "exp", "Tener sexo en el baño de un bar o una disco"],
    [3, "exp", "Tener sexo en la oficina o en mi lugar de trabajo"],
    [3, "exp", "Tener sexo en el probador de una tienda"],
    [3, "exp", "Tener sexo en un avión, bus o tren"],
    [3, "exp", "Tener sexo en un parque o al aire libre"],
    [3, "exp", "Tener sexo en un ascensor"],
    [3, "exp", "Tener sexo en el cine"],
    [3, "exp", "Tener sexo en la cama de amigos o familiares sin que lo supieran"],
    [3, "exp", "Ir a un strip club o show para adultos"],
    [3, "exp", "Hacer un striptease para alguien"],
    [3, "exp", "Que me hagan un baile erótico privado"],
    [3, "exp", "Tener sexo con dos personas distintas en un mismo día"],
    [3, "exp", "Tener sexo con copete fuerte encima"],
    [3, "exp", "Tener sexo en un sauna o baño termal"],
    [3, "exp", "Recibir un masaje que terminó en algo sexual"],
    [3, "exp", "Bañarme desnudo/a en el mar o una piscina con más gente"],
    [3, "exp", "Tener sexo en la terraza o el balcón"],
    [3, "exp", "Tener sexo en la cocina o en la mesa del comedor"],
    [3, "exp", "Tener sexo en una fiesta con gente al otro lado de la puerta"],
    [3, "exp", "Tener sexo en un estacionamiento"],
    [3, "exp", "Tener sexo con alguien famoso o conocido"],
    [4, "exp", "Hacer un trío"],
    [4, "exp", "Ir a un bar swinger o club de intercambio"],
    [4, "exp", "Intercambiar pareja con otra pareja"],
    [4, "exp", "Tener una relación abierta"],
    [4, "exp", "Tener sexo con dos personas del mismo grupo de amigos"],
    [4, "exp", "Participar en sexo grupal"],
    [4, "exp", "Tener sexo mientras otra persona miraba"],
    [4, "exp", "Mirar a otras personas tener sexo en vivo"],
    [4, "exp", "Ir a una playa nudista"],
    [4, "exp", "Hacer un trío con mi pareja y otra persona"],
    [4, "exp", "Hacer un trío con dos personas que conocí esa misma noche"],
    [4, "exp", "Probar el poliamor"],
    [4, "exp", "Tener sexo con más de una persona en menos de 24 horas"],
    [4, "exp", "Tener sexo con alguien de mi mismo sexo estando en una relación con alguien del otro"],
    [4, "conf", "Haber tenido sexo con más de 30 personas en mi vida"],
    [4, "gusto", "¿Con quién harías un trío?", ["Dos hombres", "Dos mujeres", "Un hombre y una mujer", "Con nadie"]],
    [4, "gusto", "¿Relación abierta?", ["Sí, sin problema", "Solo con reglas claras", "Jamás"]],
    [5, "exp", "Participar en una orgía con desconocidos"],
    [5, "exp", "Tener sexo en un club de sexo o darkroom"],
    [5, "exp", "Hacer un trío donde todos hicieron de todo con todos"],
    [5, "exp", "Probar la doble penetración"],
    [5, "exp", "Que mi pareja tenga sexo con otra persona mientras yo miro"],
    [5, "exp", "Tener sexo con gente mirando alrededor"],
    [5, "exp", "Grabar sexo grupal con permiso de todos"],
    [1, "exp", "Tener una cita en el lugar más romántico de mi ciudad"],
    [1, "exp", "Tener un amor de verano que siguió después de las vacaciones"],
    [2, "exp", "Tener sexo en un lugar con una vista espectacular"],
    [2, "exp", "Tener sexo en un hotel de lujo"],
    [2, "exp", "Tener sexo en el sofá con gente durmiendo en la casa"],
    [2, "exp", "Tener sexo en plena jornada de teletrabajo"],
    [2, "exp", "Tener sexo en una cabaña en la nieve"],
    [2, "exp", "Tener sexo en un bote o una lancha"],
    [2, "exp", "Tener sexo al aire libre bajo las estrellas"],
    [2, "conf", "Tener sexo con alguien la misma noche que terminé con mi pareja"],
    [2, "gusto", "¿Dónde es mejor?", ["En la cama", "En la ducha", "En el sofá", "En el auto", "Al aire libre"]],
    [3, "exp", "Tener sexo en un mirador con autos al lado"],
    [3, "exp", "Tener sexo en una piscina de un hotel o un club"],
    [3, "exp", "Tener sexo en una escalera de emergencia"],
    [3, "exp", "Tener sexo en un camarín o vestuario"],
    [3, "exp", "Tener sexo en la playa de día"],
    [3, "exp", "Tener sexo en la pieza de un hostal compartido"],
    [3, "exp", "Tener sexo en un auto en movimiento"],
    [3, "exp", "Tener sexo en la casa de un desconocido después de una fiesta"],
    [3, "exp", "Tener sexo con alguien que acababa de conocer en un bar, esa misma noche"],
    [3, "conf", "Haber tenido sexo con alguien de este grupo"],
    [3, "gusto", "¿Qué lugar público te daría más morbo?", ["Un avión", "Un probador", "La playa", "La oficina", "Un ascensor"]],
    [4, "exp", "Tener sexo con dos personas que eran pareja entre ellas"],
    [4, "exp", "Ir a una fiesta erótica o temática para adultos"],
    [4, "exp", "Tener sexo mientras otra pareja lo hacía en la misma pieza"],
    [4, "exp", "Hacer un trío con dos personas de mi mismo sexo"],
    [4, "exp", "Contratar un show erótico privado para una despedida"],
    [4, "exp", "Tener sexo con una persona casada, con permiso de su pareja"],
    [4, "conf", "Tener sexo con más de 3 personas en un mismo fin de semana"],
    [5, "exp", "Tener sexo con 3 o más personas al mismo tiempo"],
    [5, "exp", "Hacer un intercambio completo con otra pareja"],
    [5, "exp", "Tener sexo en un auto con gente mirando desde afuera (dogging)"],
    [5, "exp", "Tener sexo mientras hablaba por teléfono con otra persona"],
    [5, "exp", "Hacer un trío con mi pareja y un desconocido"],
  ],

  juguetes: [
    [1, "exp", "Comprar ropa interior especial pensando en una cita"],
    [1, "exp", "Entrar a un sex shop solo a mirar"],
    [1, "exp", "Regalar algo de sex shop como broma en un cumpleaños o despedida"],
    [1, "exp", "Usar un disfraz sexy en Halloween pensando en alguien"],
    [1, "gusto", "¿Qué ropa interior te parece más atractiva?", ["Encaje", "Deportiva", "Colores oscuros", "Ninguna"]],
    [2, "exp", "Comprar lencería o ropa interior provocativa para una ocasión especial"],
    [2, "exp", "Comprar algo en un sex shop"],
    [2, "exp", "Usar aceites o velas de masaje en la intimidad"],
    [2, "exp", "Usar lubricante con sabor"],
    [2, "exp", "Jugar a un juego de mesa o de cartas erótico en pareja"],
    [2, "exp", "Usar comida (crema, chocolate, frutillas) en el juego previo"],
    [2, "exp", "Usar hielo en el juego previo"],
    [2, "exp", "Jugar strip póker o un juego donde se pierde ropa"],
    [2, "exp", "Usar preservativos de sabores o texturas"],
    [2, "gusto", "¿Qué te parece que tu pareja tenga juguetes sexuales?", ["Me encanta", "Me da lo mismo", "Me incomoda"]],
    [3, "exp", "Usar un vibrador"],
    [3, "exp", "Usar un juguete sexual en pareja"],
    [3, "exp", "Usar esposas o amarras suaves"],
    [3, "exp", "Usar vendas en los ojos en la intimidad"],
    [3, "exp", "Usar un disfraz o hacer juegos de rol en la intimidad"],
    [3, "exp", "Regalarle un juguete sexual a mi pareja"],
    [3, "exp", "Usar un juguete controlado a distancia por una app"],
    [3, "exp", "Usar un anillo vibrador"],
    [3, "exp", "Usar plumas o pinzas para estimular"],
    [3, "exp", "Usar un succionador de clítoris"],
    [3, "exp", "Usar un masturbador masculino"],
    [3, "conf", "Que alguien encuentre mis juguetes sexuales"],
    [3, "conf", "Esconder un juguete sexual en un lugar insólito para que nadie lo encontrara"],
    [3, "conf", "Que un juguete sexual se quedara sin batería en el mejor momento"],
    [3, "gusto", "¿Cuántos juguetes sexuales tienes?", ["Ninguno", "1 o 2", "De 3 a 5", "Tengo colección"]],
    [3, "gusto", "¿Qué tipo de juguete prefieres?", ["Vibrador", "Succionador", "Anillo", "Esposas o vendas", "Ninguno"]],
    [4, "exp", "Usar un juguete controlado a distancia en un lugar público"],
    [4, "exp", "Usar un látigo o fusta suave"],
    [4, "exp", "Usar un collar o una correa en un juego de rol"],
    [4, "exp", "Usar un columpio sexual o un mueble especial"],
    [4, "exp", "Usar un arnés"],
    [4, "exp", "Usar una máquina sexual"],
    [4, "exp", "Usar una mordaza en un juego de rol"],
    [4, "exp", "Usar un juguete sexual durante una videollamada"],
    [4, "exp", "Usar pinzas para pezones"],
    [5, "exp", "Usar un plug anal"],
    [5, "exp", "Usar bolas chinas"],
    [5, "exp", "Usar bolas anales"],
    [5, "exp", "Introducir un juguete sexual en mi ano"],
    [5, "exp", "Usar un juguete doble con mi pareja"],
    [5, "exp", "Usar un vibrador en el ano de mi pareja"],
    [5, "exp", "Usar un arnés para penetrar a mi pareja"],
    [5, "exp", "Salir a una cena o carrete con un plug anal puesto"],
    [5, "exp", "Usar un juguete para estimular la próstata"],
    [5, "exp", "Usar un dildo de tamaño muy grande"],
    [1, "exp", "Mirar lencería o juguetes en una tienda online y cerrar la pestaña rápido"],
    [1, "conf", "Que un familiar recibiera por mí un pedido de sex shop"],
    [2, "exp", "Usar un disfraz sexy para sorprender a mi pareja"],
    [2, "exp", "Usar ropa interior comestible"],
    [2, "exp", "Jugar con dados eróticos"],
    [2, "exp", "Tener ropa especial solo para la intimidad"],
    [2, "gusto", "¿Qué regalo erótico te gustaría recibir?", ["Lencería", "Un juguete", "Un masaje con aceites", "Un juego erótico"]],
    [3, "exp", "Usar un vibrador en pareja durante el sexo"],
    [3, "exp", "Ir con mi pareja a comprar un juguete sexual a una tienda"],
    [3, "exp", "Usar un antifaz y guantes de seda para estimular"],
    [3, "exp", "Usar un vibrador de bolsillo"],
    [3, "exp", "Usar un lubricante con efecto calor o frío"],
    [3, "conf", "Que sonara un vibrador en el momento menos oportuno"],
    [3, "conf", "Olvidar un juguete sexual en un hotel o en la casa de alguien"],
    [4, "exp", "Usar cuerdas de bondage"],
    [4, "exp", "Usar un juguete con cadenas"],
    [4, "exp", "Usar un traje de látex o de cuero"],
    [4, "exp", "Usar un juguete sexual con mi pareja delante de otra persona"],
    [4, "exp", "Usar un vibrador por más de una hora seguida"],
    [4, "gusto", "¿Qué te da más curiosidad?", ["Cuerdas y amarras", "Látigos", "Juguetes a control remoto", "Máquinas sexuales", "Nada"]],
    [5, "exp", "Usar un plug anal con cola o joya"],
    [5, "exp", "Usar dilatadores anales"],
    [5, "exp", "Usar un juguete de electroestimulación"],
    [5, "exp", "Usar un dildo doble con arnés"],
    [5, "exp", "Usar un vibrador anal en público"],
  ],

  fantasias: [
    [1, "exp", "Tener un crush con un personaje de ficción"],
    [1, "exp", "Tener un crush con una celebridad muy extraña"],
    [1, "exp", "Soñar románticamente con alguien que conozco de verdad"],
    [1, "gusto", "¿Qué te parece más romántico?", ["Una cena con velas", "Un viaje sorpresa", "Una carta escrita a mano", "Cocinar juntos"]],
    [1, "gusto", "¿Qué tipo de persona te atrae más?", ["Misteriosa", "Divertida", "Inteligente", "Deportista", "Artista"]],
    [2, "exp", "Tener un sueño erótico con alguien de mi trabajo o universidad"],
    [2, "exp", "Tener un sueño erótico con alguien de este grupo"],
    [2, "exp", "Tener una fantasía con un profesor, profesora o jefe"],
    [2, "exp", "Tener una fantasía con un desconocido de la calle o el transporte público"],
    [2, "exp", "Tener una fantasía con la pareja de un amigo o amiga"],
    [2, "exp", "Ver pornografía con mi pareja"],
    [2, "exp", "Leer o escuchar relatos eróticos"],
    [2, "exp", "Contarle a mi pareja una fantasía que nunca le había dicho a nadie"],
    [2, "conf", "Imaginar a otra persona mientras estaba con mi pareja"],
    [2, "gusto", "¿Luces prendidas o apagadas?", ["Prendidas", "Apagadas", "Media luz"]],
    [2, "gusto", "¿Qué te excita más?", ["Lo que se dice", "Lo que se ve", "Lo que se toca", "Lo que se imagina"]],
    [2, "gusto", "¿Música durante el sexo?", ["Sí, siempre", "A veces", "Nunca, me distrae"]],
    [2, "gusto", "¿Cuántas veces a la semana sería lo ideal?", ["1", "2 o 3", "De 4 a 6", "Todos los días"]],
    [2, "gusto", "¿Rapidito o sin apuro?", ["Rapidito", "Sin apuro", "Depende del día"]],
    [2, "gusto", "¿Qué parte del cuerpo te parece más sexy?", ["Ojos", "Boca", "Cuello", "Espalda", "Manos", "Trasero"]],
    [2, "gusto", "¿Qué es lo más importante en la cama?", ["La química", "La confianza", "La experiencia", "Las ganas"]],
    [3, "exp", "Hacer un juego de rol (jefe y empleada, doctor y paciente, policía y detenido)"],
    [3, "exp", "Hablar sucio durante el sexo"],
    [3, "exp", "Tener sexo con la ropa puesta por el apuro"],
    [3, "exp", "Que me dominen en la cama"],
    [3, "exp", "Dominar a mi pareja en la cama"],
    [3, "exp", "Tener sexo frente a un espejo"],
    [3, "exp", "Grabar audios eróticos para mi pareja"],
    [3, "exp", "Tener una fantasía recurrente con dos personas al mismo tiempo"],
    [3, "exp", "Cumplir una fantasía que tenía hace años"],
    [3, "exp", "Probar el sexo tántrico"],
    [3, "exp", "Tener sexo en silencio total porque había gente cerca"],
    [3, "gusto", "¿En la cama prefieres?", ["Dominar", "Que me dominen", "Ir cambiando"]],
    [3, "gusto", "¿Qué fantasía cumplirías primero?", ["Lugar público", "Juego de rol", "Trío", "Grabarnos"]],
    [4, "exp", "Practicar BDSM"],
    [4, "exp", "Que me den nalgadas durante el sexo"],
    [4, "exp", "Dar nalgadas durante el sexo"],
    [4, "exp", "Que me tiren el pelo durante el sexo"],
    [4, "exp", "Tener sexo con los ojos vendados y las manos amarradas"],
    [4, "exp", "Tener un fetiche con los pies"],
    [4, "exp", "Tener un fetiche con la ropa interior o los uniformes"],
    [4, "exp", "Practicar exhibicionismo con mi pareja (que otros nos miren)"],
    [4, "exp", "Masturbarme frente a mi pareja"],
    [4, "exp", "Masturbarnos juntos mirándonos"],
    [4, "exp", "Mirar a mi pareja masturbarse"],
    [4, "exp", "Usar cera de vela caliente en el cuerpo"],
    [4, "gusto", "¿Posición favorita?", ["Misionero", "Encima", "En cuatro", "De lado", "De pie"]],
    [4, "gusto", "¿Qué disfrutas más?", ["Dar", "Recibir", "Las dos cosas"]],
    [5, "exp", "Practicar sexo anal"],
    [5, "exp", "Recibir sexo anal"],
    [5, "exp", "Que terminen en mi boca"],
    [5, "exp", "Que terminen en mi cara"],
    [5, "exp", "Practicar el 69"],
    [5, "exp", "Hacer sexo oral anal"],
    [5, "exp", "Recibir sexo oral anal"],
    [5, "exp", "Tener o provocar un squirt"],
    [5, "exp", "Tener sexo durante la menstruación"],
    [5, "exp", "Practicar la garganta profunda"],
    [5, "exp", "Practicar lluvia dorada"],
    [5, "exp", "Practicar fisting"],
    [5, "gusto", "¿Qué prefieres?", ["Sexo oral", "Penetración", "Un juego previo largo"]],
    [5, "gusto", "¿Dónde prefieres que termine tu pareja?", ["Adentro", "Afuera", "En la boca", "Donde quiera"]],
    [1, "gusto", "¿Qué te enamora más?", ["Una mirada", "Una sonrisa", "Una voz", "Un olor", "Unas manos"]],
    [2, "exp", "Tener una fantasía con alguien del gimnasio"],
    [2, "exp", "Tener una fantasía con un vecino o una vecina"],
    [2, "exp", "Contarle a mi pareja con quién he tenido sueños eróticos"],
    [2, "gusto", "¿Qué te prende más de otra persona?", ["Su seguridad", "Su voz", "Su olor", "Cómo me mira", "Su humor"]],
    [3, "exp", "Tener sexo con una playlist elegida especialmente para el momento"],
    [3, "exp", "Hacer un juego de rol con disfraz completo"],
    [3, "exp", "Tener sexo sin poder hacer ruido como parte del juego"],
    [3, "exp", "Hacerle un striptease con música a mi pareja"],
    [3, "exp", "Mandarle a mi pareja una lista de fantasías para cumplir"],
    [3, "exp", "Que me venden los ojos y tener que adivinar qué me están haciendo"],
    [3, "gusto", "¿Cuánto debería durar el juego previo?", ["5 minutos", "15 minutos", "Media hora", "Lo que haga falta"]],
    [4, "exp", "Tener la fantasía de que me miren desconocidos"],
    [4, "exp", "Hacer juegos de dominación con reglas y palabra de seguridad"],
    [4, "exp", "Tener sexo mientras mi pareja me da órdenes"],
    [4, "exp", "Tener un fetiche con el cuero o el látex"],
    [4, "exp", "Que me amarren a la cama"],
    [4, "exp", "Hacer un juego de rol de desconocidos que se conocen en un bar"],
    [4, "exp", "Tener sexo sabiendo que otros nos estaban escuchando"],
    [4, "gusto", "¿Qué práctica intensa te da más curiosidad?", ["Dominación", "Amarras", "Exhibicionismo", "Juegos de rol", "Ninguna"]],
    [5, "exp", "Hacer sexo oral en un lugar público"],
    [5, "exp", "Recibir sexo oral en un lugar público"],
    [5, "exp", "Tener un orgasmo solo con sexo anal"],
    [5, "exp", "Practicar el edging (retrasar el orgasmo una y otra vez)"],
    [5, "exp", "Tener orgasmos múltiples"],
    [5, "exp", "Practicar el pegging"],
    [5, "gusto", "¿Qué práctica te da más curiosidad?", ["Anal", "Pegging", "Tríos", "Edging", "Ninguna"]],
  ],

  secretos: [
    [1, "conf", "Revisar el celular de mi pareja a escondidas"],
    [1, "conf", "Mentirle a mi pareja sobre dónde estaba"],
    [1, "conf", "Sentir celos de un amigo o amiga de mi pareja"],
    [1, "conf", "Tener pareja y que me gustara otra persona en secreto"],
    [1, "conf", "Coquetear por chat con alguien estando en pareja"],
    [1, "conf", "Esconderle a mi pareja cuánto gasté en algo"],
    [1, "conf", "Fingir que me gustaba un regalo de mi pareja"],
    [1, "conf", "Salir con alguien solo porque pagaba todo"],
    [1, "conf", "Mentir sobre mi número de exparejas"],
    [1, "conf", "Seguir con alguien por lástima"],
    [1, "conf", "Fingir que no me importaba que alguien estuviera con otra persona"],
    [1, "gusto", "¿Revisar el celular de la pareja es...?", ["Normal", "Solo si hay sospechas", "Nunca, es de cada uno"]],
    [1, "gusto", "¿Perdonarías una infidelidad?", ["Sí", "Depende", "Jamás"]],
    [1, "gusto", "¿Qué infidelidad es peor?", ["Infidelidad física", "Infidelidad emocional", "Las dos igual"]],
    [2, "conf", "Ser infiel emocionalmente (coquetear y hablar en secreto con otra persona)"],
    [2, "conf", "Ser infiel físicamente al menos una vez"],
    [2, "conf", "Que me fueran infiel y enterarme"],
    [2, "conf", "Ser \"el otro\" o \"la otra\" en una relación"],
    [2, "conf", "Besar a alguien estando en pareja"],
    [2, "conf", "Fingir un orgasmo"],
    [2, "conf", "Fingir que me quedé dormido/a para no tener sexo"],
    [2, "conf", "Decirle a alguien que fue lo mejor sin que fuera cierto"],
    [2, "conf", "Volver con un ex solo porque el sexo era muy bueno"],
    [2, "conf", "Tener una relación donde lo único que funcionaba era la cama"],
    [2, "conf", "Arrepentirme al día siguiente de haberme acostado con alguien"],
    [2, "conf", "Acostarme con alguien sabiendo que tenía pareja"],
    [2, "conf", "Tener sexo con alguien solo por despecho"],
    [2, "gusto", "¿Le contarías a tu pareja con cuántas personas has estado?", ["Sí, todo", "Solo un número aproximado", "Nunca"]],
    [3, "conf", "Tener un amante durante varios meses"],
    [3, "conf", "Acostarme con el ex de un amigo o amiga"],
    [3, "conf", "Acostarme con alguien de la familia de mi pareja"],
    [3, "conf", "Ser infiel en una despedida de soltero o soltera"],
    [3, "conf", "Acostarme con alguien casado o casada"],
    [3, "conf", "Tener un \"amigo con derechos\" por más de un año sin que nadie lo supiera"],
    [3, "conf", "Tener que escapar por una ventana o una puerta trasera para que no me pillaran"],
    [3, "conf", "Acostarme con dos personas del mismo grupo de amigos sin que lo supieran"],
    [3, "conf", "Ser infiel con alguien de este grupo o del círculo cercano"],
    [3, "conf", "Tener sexo con alguien en la cama que compartía con mi pareja"],
    [4, "conf", "Ser infiel con más de una persona al mismo tiempo"],
    [4, "conf", "Hacer un trío siendo infiel"],
    [4, "conf", "Tener una doble vida amorosa durante años"],
    [1, "conf", "Hablar mal de mi pareja con mis amigos"],
    [1, "conf", "Esconder que seguía hablando con mi ex"],
    [1, "conf", "Decir que no había visto un mensaje para no tener que responderlo"],
    [1, "conf", "Tener celos de alguien de este grupo"],
    [2, "conf", "Coquetear con alguien del trabajo teniendo pareja"],
    [2, "conf", "Salir con alguien sabiendo que le gustaba a mi mejor amigo o amiga"],
    [2, "conf", "Terminar con alguien por otra persona y no decírselo"],
    [2, "conf", "Descubrir a mi pareja con otra persona"],
    [2, "conf", "Perdonar una infidelidad"],
    [2, "gusto", "Después de terminar, ¿cuánto hay que esperar para estar con alguien más?", ["Nada", "Un par de semanas", "Unos meses", "Lo que haga falta"]],
    [3, "conf", "Ser infiel en un viaje"],
    [3, "conf", "Acostarme con la pareja de un amigo o amiga"],
    [3, "conf", "Acostarme con alguien solo para vengarme de una infidelidad"],
    [3, "conf", "Tener una aventura con un compañero o compañera de trabajo"],
    [3, "conf", "Mandarle mensajes calientes a alguien mientras mi pareja dormía al lado"],
    [4, "conf", "Tener una relación secreta con dos personas del mismo círculo"],
    [4, "conf", "Ser infiel con la ex pareja de mi pareja"],
  ],

  verguenza: [
    [1, "conf", "Que me pillen stalkeando a alguien"],
    [1, "conf", "Tropezar o caerme en plena cita"],
    [1, "conf", "Llamar a mi pareja con el nombre de mi ex"],
    [1, "conf", "Que mis papás leyeran un chat romántico mío"],
    [1, "conf", "Tener mal aliento en un primer beso"],
    [1, "conf", "Que me pillen ensayando una declaración frente al espejo"],
    [1, "conf", "Quedarme dormido/a en una cita"],
    [1, "conf", "Mandar un mensaje de amor al grupo de la familia por error"],
    [1, "conf", "Que me pillen mirando fijo a alguien que me gustaba"],
    [1, "conf", "Llorar en una cita"],
    [2, "conf", "Que un familiar o compañero de casa me pillara teniendo sexo"],
    [2, "conf", "Tener un accidente vergonzoso en la cama (calambre, caída, ruido extraño)"],
    [2, "conf", "Que no se me diera en el momento y querer desaparecer"],
    [2, "conf", "Terminar demasiado rápido"],
    [2, "conf", "Reírme en pleno momento íntimo y arruinarlo"],
    [2, "conf", "Que se rompiera un condón"],
    [2, "conf", "Que los vecinos se quejaran por el ruido"],
    [2, "conf", "Decir el nombre equivocado en la cama"],
    [2, "conf", "Que se me cayera un condón del bolsillo frente a otras personas"],
    [2, "conf", "Quedarme sin saber cómo salir de la casa de alguien a la mañana siguiente"],
    [2, "conf", "Pasar un susto de embarazo"],
    [3, "conf", "Que un guardia o la policía me pillara teniendo sexo en público"],
    [3, "conf", "Que alguien entrara a la pieza en pleno momento"],
    [3, "conf", "Tener que ir a urgencias por algo que pasó en la cama"],
    [3, "conf", "Lesionarme intentando una posición difícil"],
    [3, "conf", "Romper una cama o un mueble teniendo sexo"],
    [3, "conf", "Que una foto íntima mía llegara a alguien que no debía"],
    [4, "conf", "Que me pillaran en pleno trío"],
    [4, "conf", "Que me encontraran amarrado/a en pleno juego de rol"],
    [1, "conf", "Que me pillaran llorando con una canción romántica"],
    [1, "conf", "Saludar a alguien que me gustaba y que no me reconociera"],
    [1, "conf", "Decirle \"amor\" por error a un compañero de trabajo"],
    [1, "conf", "Que me pillaran practicando besos con una almohada"],
    [1, "conf", "Mandar un audio romántico al grupo equivocado"],
    [2, "conf", "Que se me cayera la toalla frente a alguien que no debía verme"],
    [2, "conf", "Que mis papás encontraran condones o lencería en mis cosas"],
    [2, "conf", "Quedarme dormido/a en pleno momento íntimo"],
    [2, "conf", "Que el perro o el gato interrumpiera en el mejor momento"],
    [2, "conf", "Que me diera hipo o estornudara en pleno momento íntimo"],
    [2, "conf", "Enredarme con la ropa al intentar sacármela de forma sexy"],
    [2, "conf", "Que alguien escuchara todo desde la pieza de al lado"],
    [2, "conf", "Que alguien encontrara mi historial de pornografía"],
    [3, "conf", "Que se me cayera un juguete sexual frente a otras personas"],
    [3, "conf", "Que me pillaran en el auto con los vidrios empañados"],
    [3, "conf", "Tener que explicarle a un médico cómo me lesioné en la cama"],
    [3, "conf", "Llegar con chupones o rasguños visibles a una reunión importante"],
    [3, "conf", "Que un vecino me pillara saliendo despeinado/a de un departamento ajeno"],
    [3, "conf", "Tener que esconderme porque llegó alguien en pleno momento"],
    [4, "conf", "Que alguien conocido me viera en un club swinger o una fiesta erótica"],
    [4, "conf", "Que un mensaje sobre un trío llegara al chat equivocado"],
    [5, "conf", "Tener un accidente vergonzoso durante el sexo anal"],
    [5, "conf", "Tener que ir a urgencias porque algo quedó atascado"],
  ],
};

export const PREGUNTAS_18 = Object.entries(RAW).flatMap(([tema, rows]) =>
  rows.map(([lvl, fmt, t, opts]) => (opts ? { t, fmt, lvl, tema, opts } : { t, fmt, lvl, tema }))
);
