// questions-data.js - Banco oficial de RompeHielos (800 preguntas: 100 por categoría)
export const DEFAULT_CATEGORIES = [
  {
    "id": "secretos_intimos",
    "titulo": "Secretos Cruzados & Íntimos",
    "descripcion": "Para jugar en sala: votación anónima Sí/No con desglose de intriga por género.",
    "icono": "🔥",
    "color": "#f43f5e",
    "badge": "Nuevo & Picante",
    "preguntas": [
      "He tenido relaciones sexuales con alguien de mi mismo sexo.",
      "He besado en los labios a alguien de mi mismo sexo.",
      "He besado a dos o más personas con lengua en una misma noche.",
      "He tenido sexo con más de una persona en menos de 24 horas.",
      "He participado en un trío o una experiencia con más de 2 personas.",
      "He tenido relaciones en un lugar público con riesgo de ser pillado (playa, parque, baño de bar).",
      "He tenido sexo en un auto en movimiento o estacionado en la vía pública.",
      "He ido a un motel temático.",
      "He nadado completamente desnudo en una piscina o en el mar con más gente.",
      "He tenido sexo en un jacuzzi o tina caliente.",
      "Me he sentido atraído/a por la pareja o expareja de alguien de este grupo o círculo cercano.",
      "He enviado una foto íntima (nude) a la persona equivocada por error.",
      "He fingido un orgasmo para terminar antes y poder irme a dormir.",
      "He revisado el celular de mi pareja a escondidas mientras dormía o se duchaba.",
      "He tenido una fantasía íntima con un/a compañero/a de trabajo o jefe.",
      "He tenido un 'amigo con ventaja' o 'amigovio' con quien acordamos no engancharnos y uno se enamoró.",
      "He salido con alguien solo por su dinero, estatus o porque pagaba todo.",
      "He tenido sexo en la casa de mis suegros o de los padres de mi pareja mientras ellos estaban en la habitación de al lado.",
      "He mentido descaradamente sobre mi número de parejas sexuales anteriores.",
      "He usado un juguete sexual durante una videollamada o llamada telefónica.",
      "He besado a alguien en una fiesta y al día siguiente no me acordaba ni de su nombre.",
      "He creado un perfil falso en Instagram o Tinder para espiar a alguien.",
      "He tenido relaciones en una oficina, lugar de trabajo o universidad.",
      "He tenido un sueño húmedo muy explícito con alguien que está presente en esta habitación.",
      "He seguido hablando o acostándome con un/a ex mientras estaba empezando a salir con otra persona.",
      "He hecho ghosting de la noche a la mañana a alguien con quien llevaba saliendo semanas.",
      "He tenido un 'one night stand' (sexo de una sola noche) y me fui antes de que amaneciera.",
      "He mandado mensajes subidos de tono estando borracho/a de los que me arrepentí a la mañana siguiente.",
      "He usado disfraces, juegos de rol o accesorios en la intimidad.",
      "He besado a alguien solo para poner celosa a otra persona.",
      "He terminado una relación por mensaje de WhatsApp en vez de dar la cara.",
      "He sido infiel físicamente al menos una vez en mi vida.",
      "He sido infiel emocionalmente (hablar coquetamente y en secreto) estando en pareja.",
      "Me he grabado o tomado fotos íntimas con mi pareja.",
      "He tenido sexo con alguien solo porque me sentía solo/a o aburrido/a.",
      "He tenido una experiencia íntima en un cine o transporte público.",
      "He hecho un 'striptease' o baile sensual para alguien en privado.",
      "Me he quedado a dormir en la casa de alguien con intenciones de sexo y me mandaron directo a la 'friendzone'.",
      "He tenido ganas de besar a alguien de esta sala en algún momento.",
      "He probado o me gustaría probar el poliamor o una relación abierta.",
      "He borrado conversaciones comprometedoras justo antes de ver a mi pareja.",
      "He comprado lencería o ropa interior provocativa exclusivamente para una cita específica.",
      "He tenido un encuentro íntimo con alguien con quien me llevaba pésimo solo por pura tensión sexual.",
      "He fingido estar borracho/a para justificar una tontera que hice con total consciencia.",
      "He mentido diciendo que tenía un compromiso urgente solo para escapar de una cita terrible.",
      "He tenido un crush intenso con el padre/madre de un amigo/a.",
      "He tenido un accidente íntimo vergonzoso (calambres, ruidos extraños, caídas de la cama).",
      "He besado a más de 20 personas en mi vida.",
      "He tenido sexo con más de 10 personas en mi vida.",
      "He tenido relaciones sexuales con alguien distinto a mi pareja actual sin su consentimiento.",
      "He tenido sexo sin protección con alguien que apenas conocía esa misma noche.",
      "He hecho un trío donde todos se besaron con todos.",
      "Tengo un fetiche o gusto particular que jamás le he confesado a mi familia ni a la mayoría de mis amigos.",
      "He practicado 'sexting' o enviado notas de voz explícitas mientras estaba en una reunión familiar o de trabajo.",
      "He tenido sexo con alguien solo porque me caía bien su perro o porque tenía un departamento increíble.",
      "He besado a alguien sabiendo perfectamente que tenía novio/a o prometido/a.",
      "He buscado intencionalmente a alguien en Tinder solo para una noche y nunca más contestarle.",
      "He tenido una experiencia sexual al aire libre durante el día donde alguien casi me descubre.",
      "He tenido sexo con dos personas del mismo grupo de amigos sin que ellos se enteraran entre sí.",
      "He tenido un 'crush' platónico secreto con alguien de este grupo durante meses.",
      "He usado aplicaciones de citas teniendo pareja formal.",
      "He fingido que me gustaba una posición sexual o una práctica solo por complacer a la otra persona.",
      "He tenido un encuentro íntimo en el baño de un avión, tren o bus de viaje.",
      "He sentido atracción sexual por un profesor o jefe de mi trabajo/universidad.",
      "He vuelto con un/a ex únicamente porque el sexo era demasiado bueno como para dejarlo ir.",
      "He recibido fotos íntimas no solicitadas y se las mostré a un amigo/a para reírnos.",
      "He dejado una marca o 'chupón' en el cuello de alguien a propósito para marcar territorio.",
      "He tenido una cita a ciegas que terminó directamente en un motel esa misma noche.",
      "He fingido quedarme dormido/a para evitar tener intimidad con mi pareja.",
      "He tenido sexo en la cama de mis mejores amigos o de mis hermanos sin que lo sepan.",
      "He utilizado un juguete sexual en mí o en mi pareja.",
      "He introducido un juguete sexual en mi ano.",
      "He tenido sexo telefónico o por videollamada con alguien que no conozco en persona.",
      "He sido pillado in fraganti teniendo relaciones por un familiar o amigo.",
      "He tenido una fantasía recurrente con dos personas al mismo tiempo.",
      "He tenido sexo en una carpa en un campamento con amigos durmiendo al lado.",
      "He besado a alguien solo para no quedar como el único sin besar a nadie en la fiesta.",
      "He usado comida (crema batida, chocolate, hielo) durante el juego previo.",
      "He visitado un club para adultos, strip club o bar swinger.",
      "He tenido una experiencia sexual bajo los efectos de sustancias o alcohol fuerte.",
      "He mentido diciendo que tomaba anticonceptivos o que tenía condones cuando no era así.",
      "He tenido sexo con alguien cuya ideología política o religión detesto por completo.",
      "He tenido una cita solo para conseguir una comida gratis en un restaurante caro.",
      "He tenido un sueño erótico con la celebridad más extraña o bizarra que se puedan imaginar.",
      "He probado o me gustaría probar el bondage suave, amarras o vendas en los ojos.",
      "He tenido un 'amigo con derechos' durante más de un año sin que nadie en nuestro círculo lo sospechara.",
      "He tenido que escapar por una ventana o puerta trasera para no ser descubierto/a por la pareja de alguien.",
      "He mandado una indirecta muy caliente por historias de mejores amigos de Instagram para que solo una persona la viera.",
      "He tenido sexo en el vestidor o probador de una tienda de ropa.",
      "He tenido sexo mañanero con resaca tremenda y sin lavarme los dientes primero.",
      "He recibido un masaje que empezó inocente y terminó en algo completamente explícito.",
      "He fingido que no me importaba que alguien estuviera con otra persona cuando por dentro me moría de celos.",
      "He tenido un encuentro íntimo en un sauna o baño termal.",
      "He guardado un video o foto íntima en una carpeta oculta o con contraseña en mi celular.",
      "He sentido vergüenza ajena de la forma en que alguien gemía o hablaba sucio en la cama.",
      "He tenido una relación donde lo único que funcionaba al 100% era la cama y todo lo demás era un desastre.",
      "He tenido un romance apasionado durante unas vacaciones en otra ciudad o país que duró solo unos días.",
      "He besado apasionadamente a alguien bajo la lluvia al estilo película de Hollywood.",
      "He tenido sexo con las luces completamente prendidas y frente a un espejo de cuerpo entero.",
      "He deseado intensamente en secreto tener una noche sin límites ni reglas con alguien presente aquí."
    ]
  },
  {
    "id": "dilemas_absurdos",
    "titulo": "Dilemas & Debates Absurdos",
    "descripcion": "Preguntas para discutir horas, reírse y ver la lógica retorcida de cada uno.",
    "icono": "🤯",
    "color": "#ff6b8b",
    "badge": "Popular",
    "preguntas": [
      "Si pudieras eliminar una sola cosa de la faz de la Tierra para siempre, ¿qué elegirías?",
      "¿Preferirías saber la fecha exacta de tu muerte o la causa?",
      "¿Cuál es la teoría conspirativa más ridícula que en el fondo te hace dudar un poquito?",
      "Si tu vida fuera una película, ¿en qué género caería y quién compondría la banda sonora?",
      "¿Preferirías tener que cantar todo lo que dices o bailar cada vez que caminas?",
      "¿Cuál ha sido la compra más inútil en la que has gastado plata y aún te da vergüenza recordar?",
      "Si te arrestaran hoy sin dar explicaciones a nadie, ¿qué asumirían tus amigos o familiares que hiciste?",
      "¿Preferirías poder hablar con los animales o hablar fluidamente todos los idiomas humanos?",
      "¿Qué regla no escrita de la sociedad encuentras completamente absurda?",
      "Si pudieras cenar con cualquier personaje histórico (vivo o muerto), pero solo pudieran comer completos, ¿a quién invitas?",
      "¿Qué es algo que a todo el mundo parece encantarle pero tú simplemente no soportas?",
      "Si solo pudieras comer un plato por el resto de tus días, pero con cero consecuencias de salud, ¿cuál sería?",
      "¿Preferirías viajar 200 años al pasado o 200 años al futuro?",
      "¿Cuál es el dato curioso más inútil que tienes grabado en la memoria?",
      "Si tuvieras que cambiar de nombre mañana mismo, ¿cuál elegirías?",
      "¿Qué trabajo que ya no existe revivirías solo por diversión?",
      "Si pudieras poner un mensaje en una pantalla gigante en medio de la ciudad para que todos lo lean por una hora, ¿qué escribirías?",
      "¿Preferirías no volver a escuchar música nunca más o no volver a ver series/películas?",
      "¿Cuál ha sido la situación más surrealista o de 'trágame tierra' que has vivido en un lugar público?",
      "Si te pagaran un millón de dólares pero tuvieras que pasar un año entero sin usar internet ni smartphone, ¿aceptarías?",
      "¿Preferirías ser la persona más inteligente del mundo en una sociedad mediocre o una persona promedio en un mundo de genios?",
      "Si pudieras convertirte en fantasma por 24 horas y nadie te viera, ¿qué sería lo primero que harías?",
      "¿Preferirías poder rebobinar 10 segundos de tu vida cada vez que quieras o pausar el tiempo por 10 minutos al día?",
      "¿Qué crimen menor cometerías si supieras con 100% de certeza que jamás te descubrirán?",
      "¿Preferirías vivir sin poder mentir nunca jamás o que todos sepan exactamente cuándo estás mintiendo?",
      "Si los alienígenas invadieran la Tierra y te pidieran un solo disco de música para juzgar a la humanidad, ¿cuál les entregas?",
      "¿Preferirías tener hipo crónico cada vez que te ríes o estornudar cada vez que te excitas?",
      "Si pudieras elegir cómo reencarnar en tu próxima vida, ¿en qué animal, objeto o ser volverías?",
      "¿Preferirías poder teletransportarte a cualquier lugar pero llegar siempre completamente desnudo o viajar gratis en primera clase pero tardando el doble?",
      "Si un día te despiertas y todos los humanos desaparecieron excepto tú y una persona que te cae pésimo, ¿qué harías?",
      "¿Preferirías que tus pensamientos se proyecten como subtítulos sobre tu cabeza o que tu historial de internet sea público?",
      "Si tuvieras que pelear a muerte contra 50 patos del tamaño de un caballo o 1 caballo del tamaño de un pato, ¿qué eliges?",
      "¿Preferirías no volver a sentir dolor físico nunca más o tener inmunidad total contra cualquier enfermedad?",
      "Si tuvieras que borrar de la historia a una de estas cosas: el café, el queso, el alcohol o el chocolate, ¿cuál sacrificas?",
      "¿Preferirías poder respirar bajo el agua o ser capaz de volar a la velocidad de una bicicleta?",
      "Si pudieras saber la verdad absoluta sobre un solo misterio de la humanidad (alienígenas, vida tras la muerte, Atlantis, etc.), ¿cuál eliges?",
      "¿Preferirías tener que decir en voz alta todo lo que piensas durante 24 horas o no poder hablar por 6 meses?",
      "Si tuvieras un clon exacto de ti mismo, ¿se llevarían increíble o no se soportarían ni 10 minutos?",
      "¿Preferirías vivir en un mundo donde nunca existe la noche o donde nunca sale el sol?",
      "Si pudieras cambiar una sola decisión que tomaste en los últimos 5 años, ¿cuál cambiarías sin pensarlo dos veces?",
      "¿Preferirías poder leer la mente de cualquiera pero solo cuando esa persona está pensando algo negativo sobre ti?",
      "Si tuvieras que pasar 1 mes atrapado en un reality show de televisión abierta, ¿cuál elegirías?",
      "¿Preferirías que cada vez que entras a una habitación suene una música épica de presentación o que nadie note jamás tu presencia?",
      "Si pudieras intercambiar de cuerpo con cualquier persona famosa por una semana, ¿quién sería y qué harías con su dinero?",
      "¿Preferirías tener la habilidad de convencer a cualquiera de cualquier mentira o saber siempre cuándo alguien te dice la verdad?",
      "Si pudieras presionar un botón que te da 10 millones de dólares pero hace que una persona desconocida al azar en el mundo pierda todos sus recuerdos, ¿lo presionas?",
      "¿Preferirías tener manos del tamaño de pelotas de básquetbol o pies del tamaño de patinetas?",
      "Si un genio te concede 3 deseos pero tu peor enemigo recibe el doble de todo lo que pides, ¿qué pedirías?",
      "¿Preferirías tener 10 años más de vida con salud perfecta o 500.000 dólares ahora mismo?",
      "¿Qué objeto cotidiano moderno colapsaría más rápido a la sociedad si desapareciera de un minuto a otro?",
      "¿Preferirías tener que comer todo con cuchara para siempre o no poder usar cuchillos nunca más?",
      "Si pudieras viajar en el tiempo solo como observador invisible, ¿a qué evento histórico irías primero?",
      "¿Preferirías poder comunicarte con fantasmas o poder ver el futuro en tus sueños pero no poder cambiarlo?",
      "Si pudieras crear una ley universal que castigue con cárcel inmediata una conducta social molesta, ¿cuál castigarías?",
      "¿Preferirías no tener que dormir nunca más sin sufrir cansancio o no tener que comer nunca más sin pasar hambre?",
      "Si te ofrecieran vivir en una simulación de realidad virtual donde eres el ser más feliz y exitoso, ¿te desconectarías alguna vez?",
      "¿Preferirías tener una memoria fotográfica infinita o la capacidad de olvidar voluntariamente cualquier recuerdo doloroso?",
      "Si pudieras ponerle fin a la pobreza en el mundo pero tú tuvieras que vivir en la indigencia absoluta el resto de tus días, ¿lo harías?",
      "¿Preferirías envejecer físicamente hacia atrás como Benjamin Button o quedarte estancado en tus 18 años para siempre?",
      "Si tuvieras que pasar 1 año entero en una isla desierta con 3 personas de este grupo, ¿a quiénes eliges para sobrevivir?",
      "¿Preferirías perder para siempre el sentido del gusto o el sentido del olfato?",
      "Si descubrieras que la Tierra es efectivamente una simulación por computadora para entretener a una raza alienígena, ¿cambiaría en algo tu forma de vivir?",
      "¿Preferirías que la gente te recuerde como una persona brillante pero antipática o como una persona mediocre pero entrañable y querida?",
      "Si pudieras tener un botón de 'mute' en la vida real para silenciar a una persona durante 1 hora al día, ¿con quién lo usarías más?",
      "¿Preferirías tener dientes de oro brillante o cabello de color verde flúor permanente?",
      "Si pudieras domesticar a cualquier animal salvaje del planeta para que sea tu mascota fiel, ¿cuál tendrías?",
      "¿Preferirías poder teletransportarte solo a lugares donde ya has estado o volar solo a 2 metros de altura del suelo?",
      "Si pudieras revivir a un solo músico o artista de la historia para un último recital exclusivo para ti y tus amigos, ¿a quién revives?",
      "¿Preferirías tener un mapa mental perfecto que te guía a cualquier tesoro perdido o un detector infalible de mentiras?",
      "Si se inventara una pastilla que elimina para siempre la necesidad de hacer ejercicio manteniendo tu cuerpo en forma óptima, ¿cuánto pagarías por ella?",
      "¿Preferirías pasar 5 años en la cárcel con lujos de hotel 5 estrellas o 1 año en una prisión común y corriente?",
      "Si pudieras elegir el día de la semana que dura 48 horas en vez de 24, ¿cuál alargarías?",
      "¿Preferirías poder controlar el clima de tu ciudad o poder controlar los semáforos a tu antojo?",
      "Si tuvieras que elegir entre salvar la vida de tu perro/gato o la vida de un extraño con quien no tienes ninguna relación, ¿qué harías con la mano en el corazón?",
      "¿Preferirías tener visión nocturna perfecta o la capacidad de ver a través de las paredes como Superman?",
      "Si te ofrecieran saber el significado exacto y el origen del universo pero no pudieras contárselo a nadie por el resto de tu vida, ¿aceptarías saberlo?",
      "¿Preferirías no poder usar zapatos nunca más o tener que usar guantes de invierno permanentemente?",
      "Si pudieras prohibir para siempre un género musical en todo el planeta, ¿cuál desaparece de la faz de la Tierra?",
      "¿Preferirías que tu vida tenga una voz en off sarcástica que narra todo lo que haces o tener una banda de mariachis que te sigue a todos lados?",
      "Si pudieras viajar al espacio exterior a explorar planetas habitables sabiendo que jamás podrás regresar a la Tierra, ¿te subirías a la nave?",
      "¿Preferirías tener 5 hijos traviesos o 15 gatos en un departamento pequeño?",
      "Si pudieras hacer que un solo alimento chatarra sea el más nutritivo y saludable del mundo, ¿cuál elegirías?",
      "¿Preferirías poder hablar con los bebés recién nacidos o poder hablar con las plantas de tu casa?",
      "Si pudieras saber qué opina exactamente de ti cada persona que te cruzas en la calle por 10 segundos, ¿lo activarías?",
      "¿Preferirías que tu teléfono celular nunca se descargue jamás o tener internet satelital de máxima velocidad ilimitado en cualquier rincón del mundo?",
      "Si pudieras resetear el gobierno y las fronteras de todos los países del mundo y empezar de cero, ¿crees que el mundo sería mejor o peor?",
      "¿Preferirías ser famoso y millonario pero sin poder tener amigos de verdad o ser pobre pero rodeado de lealtad absoluta?",
      "Si pudieras elegir una banda sonora que suene automáticamente en tu cabeza cada vez que estás a punto de dar un beso, ¿qué canción pondrías?",
      "¿Preferirías vivir 200 años con un cuerpo de 80 o vivir 50 años en la cúspide física de tus 25?",
      "Si pudieras borrar un solo invento de la historia humana (las redes sociales, las armas, el plástico, etc.), ¿cuál borrarías?",
      "¿Preferirías ser alérgico al sol o ser alérgico al agua?",
      "Si pudieras tener un asistente robot con inteligencia artificial que hace todo por ti pero escucha todas tus conversaciones íntimas, ¿lo tendrías en tu casa?",
      "¿Preferirías no poder volver a reírte a carcajadas jamás o no poder volver a llorar nunca más?",
      "Si pudieras fusionar dos animales cualesquiera para crear una nueva especie fantástica, ¿qué animales combinarías?",
      "¿Preferirías que cada vez que mientes te crezca la nariz 2 centímetros o que se te ponga la piel de color azul pitufo?",
      "Si tuvieras la oportunidad de viajar en el tiempo y hablar 10 minutos con tu yo de 10 años, ¿qué advertencia clave le darías?",
      "¿Preferirías vivir en un apocalipsis zombie o en una distopía controlada por robots de inteligencia artificial?",
      "Si te ofrecieran 100 millones de dólares pero tienes que mudarte solo a una choza en la Antártica por 3 años sin salir de allí, ¿firmas el contrato?",
      "¿Preferirías que la gente siempre sepa cuándo estás diciendo la verdad o tener la capacidad de perdonar cualquier traición sin rencor?",
      "Si pudieras cambiar una sola regla de la física en nuestro universo por 1 hora, ¿qué fenómeno alterarías para divertirte?"
    ]
  },
  {
    "id": "citas_nivel1",
    "titulo": "Citas: Nivel 1 (Rompehielos & Gustos)",
    "descripcion": "Para primeros minutos de una cita o alguien que estás conociendo recién.",
    "icono": "☕",
    "color": "#38bdf8",
    "badge": "Citas",
    "preguntas": [
      "¿Qué es lo primero en lo que te fijas cuando conoces a alguien en persona?",
      "¿Cuál es esa comida que todo el mundo ama y tú simplemente no pasas?",
      "¿Qué serie, película o canción es tu placer culpable que defiendes a muerte?",
      "¿Qué es algo sobre ti que la mayoría de la gente malinterpreta en un primer encuentro?",
      "¿Cuál es tu lugar favorito para desconectar del mundo?",
      "¿Qué hobby o proyecto tienes ganas de empezar este año?",
      "¿Eres más de improvisar planes a última hora o tener todo organizado en un calendario?",
      "¿Cuál fue el último viaje o paseo que realmente te sorprendió?",
      "¿Qué canción pondrías para musicalizar este momento exacto?",
      "¿Cuál ha sido tu peor cita de la historia? (promesa de no juzgar)",
      "¿Qué olor te transporta inmediatamente a tu infancia?",
      "¿Cuál es tu aplicación del celular en la que más tiempo pierdes sin darte cuenta?",
      "Si abrieras un canal de YouTube o un podcast hoy mismo, ¿de qué temática sería?",
      "¿Prefieres mañanas tranquilas con café o noches largas con cerveza o vino?",
      "¿Cuál es tu talento inútil más impresionante?",
      "¿Eres más de perros, gatos o prefieres no tener mascotas?",
      "¿Qué libro, película o videojuego te cambió la forma de ver las cosas?",
      "¿Qué es lo más espontáneo o impulsivo que has hecho en los últimos seis meses?",
      "Si pudieras dominar un instrumento musical a la perfección en un segundo, ¿cuál elegirías?",
      "¿Cuál es la foto más vieja o curiosa que tienes guardada en tu galería del celular?",
      "¿Qué tema de conversación te apasiona tanto que podrías hablar por horas sin aburrirte?",
      "Si ganaras unas vacaciones con todo pagado mañana, ¿playa caribeña, montaña con nieve o ciudad histórica?",
      "¿Cuál es tu meme o sticker de WhatsApp que usas con más frecuencia?",
      "¿Qué hábito diario tienes que otros podrían encontrar bastante raro?",
      "¿Cuál fue el primer recital o concierto al que fuiste en tu vida?",
      "¿Qué es algo sencillo que te alegra el día al instante?",
      "¿Cocinas bien o eres el mejor cliente de los delivery de comida?",
      "¿Qué harías si este fin de semana se corta la luz y el internet en toda la ciudad?",
      "¿Cuál ha sido el mejor regalo que te han hecho en tu vida?",
      "Si tuvieras que definir tu personalidad en tres palabras clave, ¿cuáles serían?",
      "¿Qué opinas de la gente que aplaude cuando aterriza el avión?",
      "¿Cuál fue el primer crush famoso o de ficción que tuviste en tu vida?",
      "¿Eres de los que llega 15 minutos antes o 10 minutos tarde a todos lados?",
      "¿Qué comida típica de tu país defenderías a muerte ante un extranjero?",
      "¿Prefieres ir a un concierto multitudinario o a un bar acústico íntimo?",
      "¿Cuál es el mejor cumplido no físico que alguien te ha hecho jamás?",
      "¿Qué juego de mesa o videojuego saca tu lado más competitivo y despiadado?",
      "¿Cómo describirías tu fin de semana ideal perfecto de principio a fin?",
      "¿Qué es algo que consideras una pérdida total de dinero pero que la gente sigue comprando?",
      "Si tuvieras que cenar con los personajes de una sola serie de televisión, ¿a cuál te metes?",
      "¿Cuál es tu postre o dulce favorito al que jamás le dices que no?",
      "¿Eres de ver series de a un capítulo por semana o de maratonear temporadas completas en 1 día?",
      "¿Qué es lo más raro o gracioso que has comprado por internet a altas horas de la noche?",
      "¿Prefieres el frío del invierno para abrigarte o el calor del verano para andar en polera?",
      "¿Cuál es tu trago, cóctel o bebida favorita para empezar una buena conversación?",
      "¿Qué superpoder elegirías si solo pudieras usarlo para cosas cotidianas y flojas?",
      "¿Cuál es el apodo más ridículo con el que te llamaba tu familia de niño?",
      "¿Eres más de leer libros en papel o prefieres pantalla / audiolibros?",
      "¿Qué género de cine evitas a toda costa porque te aburre o te da miedo?",
      "¿Cuál fue el último video de TikTok, Instagram o YouTube que te hizo reír a carcajadas?",
      "¿Qué prefieres en una cita: comida rica en un restaurante o plan de cocinar juntos en casa?",
      "¿Tienes alguna fobia extraña o irracional que a otros les da risa?",
      "¿Cuál es tu lugar soñado en el mundo que tienes jurado visitar antes de morir?",
      "¿Eres de salir a bailar hasta que prendan las luces o de irte a acostar a las 2:00 AM?",
      "¿Qué es algo en lo que eres sorprendentemente malo a pesar de intentarlo muchas veces?",
      "¿Cuál es esa canción que te sabes de memoria y cantas a todo pulmón en la ducha o en el auto?",
      "¿Prefieres café de grano bien preparado o té / infusiones de hierbas?",
      "¿Cuál fue el trabajo más curioso, extraño o divertido que tuviste de adolescente?",
      "¿Qué juguete de tu infancia recuerdas con mayor cariño y nostalgia?",
      "¿Eres de los que decora su casa para Navidad o Halloween o te da pereza?",
      "¿Qué es lo primero que haces apenas te despiertas por la mañana?",
      "¿Prefieres dormir con ventana abierta o cerrada, ventilador o calefacción?",
      "¿Cuál es tu placer culpable televisivo: telenovelas, realities o documentales de crímenes reales?",
      "¿Cómo reaccionas cuando suena tu canción favorita en un bar o fiesta: te paras a bailar de inmediato o mueves la cabeza?",
      "¿Qué opinas de la pizza con piña: crimen culinario o manjar incomprendido?",
      "¿Qué idioma del mundo te gustaría aprender a hablar de forma instantánea?",
      "¿Cuál ha sido la fiesta o evento más épico al que has asistido en tu vida?",
      "¿Prefieres una conversación profunda a la luz de las velas o una tarde de risas jugando videojuegos / cartas?",
      "¿Qué objeto material que tienes en tu casa salvarías primero si hubiera un incendio (después de tus seres queridos y mascotas)?",
      "¿Cuál es tu momento favorito del día: amanecer, atardecer o la madrugada en silencio?",
      "¿Qué deporte o actividad física disfrutas practicar o mirar por televisión?",
      "¿Tienes alguna superstición o cábala que sigas religiosamente aunque sepas que es irracional?",
      "¿Qué opinas de los tatuajes: tienes, quieres tener o prefieres la piel limpia?",
      "¿Cuál ha sido la mayor locura que has hecho por cumplir un capricho del momento?",
      "¿Qué tipo de humor es el que más te hace reír: negro, absurdo, sarcástico o inocente?",
      "¿Prefieres vivir en una casa grande en el campo o en un departamento moderno en el centro de la ciudad?",
      "¿Cuál es la frase o muletilla que más repites cuando estás hablando con confianza?",
      "¿Qué documental te ha volado la cabeza recientemente y recomiendas a todos?",
      "¿Eres más de desayunos dulces (panqueques, tostadas francesas) o salados (huevos revueltos, palta)?",
      "¿Cuál ha sido la peor moda o tendencia que seguiste cuando estabas en el colegio?",
      "¿Qué talento artístico (cantar, pintar, bailar, escribir) desearías tener?",
      "¿Qué opinas de los parques de diversiones y las montañas rusas: adicto a la adrenalina o terror absoluto?",
      "¿Cuál fue la última película que viste en el cine y qué te pareció?",
      "¿Eres de los que se aprende los nombres de las calles o te guías 100% por puntos de referencia?",
      "¿Qué es lo más aventurero que has comido en un viaje a otro país o ciudad?",
      "¿Prefieres regalar cosas materiales útiles o experiencias memorables (viajes, conciertos, cenas)?",
      "¿Qué consejo le darías a alguien que está por tener su primera cita con una persona que le gusta mucho?",
      "¿Cuál es tu juego de cartas o juego de mesa predilecto cuando te juntas con amigos?",
      "¿Qué estación del año sientes que se adapta mejor a tu estado de ánimo?",
      "¿Eres de mandar audios de WhatsApp de 5 minutos o prefieres escribir mensajes cortos y precisos?",
      "¿Qué opinas sobre coincidir en gustos musicales con tu pareja: es vital o te da lo mismo?",
      "¿Cuál es el mejor restaurante o hueco de comida que has descubierto por casualidad?",
      "¿Tienes alguna habilidad inusual con tus manos o tu cuerpo (hacer trucos con la lengua, mover las orejas)?",
      "¿Cuál es el mejor viaje por carretera (roadtrip) que has hecho en tu vida?",
      "¿Qué serie de televisión podrías volver a ver desde el capítulo 1 una y otra vez sin aburrirte?",
      "¿Eres de coleccionar algo en particular (vinilos, figuras, tazas, recuerdos de viajes)?",
      "¿Qué prenda de ropa en tu clóset es tu favorita indiscutida porque te hace sentir increíble?",
      "¿Prefieres los días soleados y despejados o los días nublados y lluviosos para quedarte en cama?",
      "¿Qué es algo que aprendiste recientemente que te pareció fascinante?",
      "Si tuvieras que invitarme a un panorama que demuestre tu verdadera personalidad, ¿a dónde me llevarías?"
    ]
  },
  {
    "id": "citas_nivel2",
    "titulo": "Citas: Nivel 2 (Filtros Clave & Estilo de Vida)",
    "descripcion": "Preguntas directas y sin rodeos: hábitos, futuro, convivencia y qué buscas.",
    "icono": "🔍",
    "color": "#f59e0b",
    "badge": "Filtros",
    "preguntas": [
      "¿Fumas, vapeas o bebes alcohol habitualmente, o solo en ocasiones especiales?",
      "¿Cuál es tu postura frente a las drogas recreativas o el consumo casual?",
      "¿Quieres tener hijos en el futuro, ya tienes, o tienes claro que no?",
      "¿Con quién vives actualmente y qué tan importante es tu espacio personal?",
      "¿A qué te dedicas en el día a día y qué relación tienes con tu trabajo (pasión o medio de vida)?",
      "¿Tienes mascotas o alergias a animales? ¿Dormirían en tu cama?",
      "¿Qué buscas hoy: algo casual, ver qué fluye, o una relación con proyección seria?",
      "¿Cómo manejas tus finanzas: ahorrador meticuloso, inversionista o gastador impulsivo?",
      "¿Cuál es una 'red flag' absoluta que te hace descartar a alguien de inmediato?",
      "¿Cómo reaccionas cuando estás molesto o estresado: te aíslas o necesitas hablarlo al tiro?",
      "¿Qué tan importante es la política y la religión en tu vida y en tu pareja?",
      "¿Mantienes amistad cercana con alguna expareja? ¿Cómo lo manejas?",
      "¿Cómo repartirías los gastos en una relación formal: 50/50 exacto, proporcional al sueldo o quien invita paga?",
      "¿Qué opinas sobre revisar el celular en pareja o compartir contraseñas?",
      "¿Qué tan fiestero/a eres los fines de semana vs quedarte en cama viendo series?",
      "¿Qué harías si tu familia o tus mejores amigos desaprueban abiertamente a la persona con quien sales?",
      "¿Cuál es tu postura sobre el matrimonio o la convivencia bajo el mismo techo?",
      "¿Qué tan importante es la vida sexual y la compatibilidad en la cama en una escala del 1 al 10?",
      "¿Tienes deudas importantes o metas financieras grandes a corto plazo?",
      "¿Qué tan celoso/a te consideras y qué situación concreta te despierta inseguridad?",
      "¿Cuánto tiempo libre necesitas a la semana para estar a solas o con tus amigos sin tu pareja?",
      "¿Te mudarías a otra ciudad o país si a tu pareja le sale una oportunidad soñada?",
      "¿Qué es algo que consideras una 'green flag' que te hace enamorarte de inmediato?",
      "¿Cómo resuelves una discusión: con argumentos fríos, con emociones o prefieres dejar pasar el tiempo?",
      "¿Te consideras una persona rencorosa o perdonas y olvidas fácilmente?",
      "¿Qué límites consideras innegociables respecto a las salidas nocturnas con amigos?",
      "¿Qué tan dependiente eres de las redes sociales y de publicar tu vida privada?",
      "¿Crees en la fidelidad estricta para toda la vida o crees que la monogamia es un reto difícil?",
      "¿Has ido a terapia o consideras que el cuidado de la salud mental es prioritario?",
      "Si tuvieras que describir cómo fue el final de tu última relación seria, ¿qué aprendiste?",
      "¿Qué opinas de compartir amigos y salir todos juntos vs tener círculos sociales separados?",
      "¿Cómo manejas el orden y la limpieza en el hogar: maniático, relajado o caótico funcional?",
      "¿Qué harías si tu pareja gana sustancialmente más dinero que tú (o viceversa)?",
      "¿Te gusta planear vacaciones con meses de anticipación o decidir el destino sobre la marcha?",
      "¿Cuál es una costumbre o manía tuya de convivencia que tu futura pareja tendrá que soportar sí o sí?",
      "¿Qué peso tiene la opinión de tus padres en las decisiones de tu vida sentimental?",
      "¿Consideras que el coqueteo inocente en redes sociales o fiestas es una forma de infidelidad?",
      "¿Estarías dispuesto/a a firmar un acuerdo prenupcial si te casas?",
      "¿Qué harías si a tu pareja le cuesta expresar afecto en público?",
      "¿Cuál es tu mayor 'dealbreaker' (motivo de quiebre definitivo) en una relación que recién empieza?",
      "¿Cómo reaccionas si tu pareja tiene planes de salir a solas con un amigo/a del sexo opuesto?",
      "¿Qué tan tolerante eres frente a personas que cancelan citas a última hora?",
      "¿Prefieres resolver los conflictos en el mismo instante o necesitas enfriar la cabeza unas horas?",
      "¿Cuál es tu filosofía respecto a prestar dinero a amigos o pareja?",
      "¿Qué tan importante es para ti tener momentos de silencio cómodo sin necesidad de hablar?",
      "¿Cómo te llevas con tu familia y qué tan seguido los visitas o hablas con ellos?",
      "¿Qué opinas de las personas que siguen a cientos de modelos o cuentas sugestivas en Instagram?",
      "¿Estarías dispuesto/a a adoptar hijos si tu pareja no puede o no desea tener biológicos?",
      "¿Qué harías si tu pareja quiere pasar todas las fiestas de fin de año con su familia y no con la tuya?",
      "¿Cómo definirías el equilibrio ideal entre vida laboral y vida de pareja?",
      "¿Qué tipo de detalles o muestras de cariño esperas en fechas especiales (aniversarios, cumpleaños)?",
      "¿Consideras que es sano contarse el pasado sexual detallado o prefieres que quede en el misterio?",
      "¿Qué opinas sobre vivir juntos antes de casarse o comprometerse formalmente?",
      "¿Qué harías si tu pareja tiene una mascota que se porta pésimo o a la que tienes alergia?",
      "¿Cómo manejas los celos retrospectivos (obsesionarse con el pasado de la otra persona)?",
      "¿Qué nivel de ambición profesional esperas en una pareja?",
      "¿Estarías dispuesto/a a mantener económicamente a tu pareja durante una etapa de crisis o estudios?",
      "¿Qué opinas sobre las relaciones a larga distancia: funcionan o están destinadas al fracaso?",
      "¿Cómo te gustaría celebrar una boda: fiesta masiva con 200 personas o viaje íntimo con 10 amigos?",
      "¿Qué límites tienes respecto al consumo de pornografía estando en una relación formal?",
      "¿Qué harías si descubres que tu pareja tiene un secreto financiero importante que no te contó?",
      "¿Cuál es tu concepto de lealtad cuando tu pareja no está presente en la habitación?",
      "¿Qué tan importante es para ti que tu pareja tenga buen sentido del humor y sepa reírse de sí misma?",
      "¿Cómo te tomas las críticas constructivas sobre tus hábitos o manías?",
      "¿Qué opinas de publicar fotos de pareja en redes sociales: obligatorio, opcional o innecesario?",
      "¿Qué harías si a tu pareja no le caen bien tus mejores amigos de toda la vida?",
      "¿Cómo reaccionas ante los cambios de planes repentinos por emergencias laborales?",
      "¿Qué opinas sobre las cuentas bancarias compartidas en una convivencia estable?",
      "¿Cuál es tu mayor miedo o inseguridad al formalizar un compromiso a largo plazo?",
      "¿Qué tan importante es para ti mantener tu independencia y tus propios pasatiempos?",
      "¿Qué harías si tu pareja cae en una depresión profunda: cómo acompañas ese proceso?",
      "¿Cómo manejas la frustración cuando las cosas no salen como las tenías planeadas?",
      "¿Qué límites consideras indispensables respecto al contacto con la familia política?",
      "¿Qué opinas sobre salir a comer o a tomar un café con alguien de quien antes estuviste enamorado/a?",
      "¿Cómo evalúas la generosidad de una persona en las primeras etapas de conocerse?",
      "¿Qué harías si tu pareja decide cambiar radicalmente de carrera o estilo de vida?",
      "¿Qué opinas de la terapia de pareja: herramienta preventiva o último recurso antes del divorcio?",
      "¿Qué tan honesto/a eres cuando algo te molesta: lo dices de inmediato o aplicas ley del hielo?",
      "¿Cómo manejas el estrés financiero cuando las cuentas aprietan a fin de mes?",
      "¿Qué significa para ti ser un 'buen compañero de equipo' en la vida cotidiana?",
      "¿Qué importancia le das al cuidado físico y a la salud en tu rutina diaria y en la de tu pareja?",
      "¿Qué harías si tu pareja no comparte tus mismas convicciones éticas o sociales fundamentales?",
      "¿Cómo defines la diferencia entre privacidad y secretismo en una relación?",
      "¿Qué opinas de celebrar mesiversarios y fechas simbólicas pequeñas?",
      "¿Cómo te gustaría repartir las tareas domésticas (cocinar, lavar ropa, limpiar baños, compras)?",
      "¿Qué harías si tu pareja te pide revisar tu celular para sentirse tranquilo/a?",
      "¿Qué valor le das a la puntualidad y cómo reaccionas ante los atrasos crónicos?",
      "¿Cómo te imaginas tu vida dentro de 10 años en términos de hogar, familia y trabajo?",
      "¿Qué opinas sobre mantener cuentas separadas para gastos personales y un fondo común para el hogar?",
      "¿Cuál ha sido la conversación más difícil que has tenido que entablar con una pareja y qué aprendiste?",
      "¿Qué señal clara te dice que una relación ya no tiene futuro y es momento de decir adiós?",
      "¿Cómo manejas el hecho de que tu pareja tenga un mejor amigo/a muy cercano del sexo opuesto?",
      "¿Qué hábitos de higiene personal consideras básicos e innegociables en la convivencia?",
      "¿Qué importancia tiene para ti que tu pareja se lleve excelente con tus padres y hermanos?",
      "¿Qué harías si tu pareja quiere mudarse a una casa de campo alejada y tú prefieres la ciudad?",
      "¿Cómo manejas los desacuerdos sobre la crianza o educación de los hijos?",
      "¿Qué actitud o comentario te hace perder el interés instantáneamente por alguien que te gustaba?",
      "¿Cómo sabes cuándo estás listo/a para dar el paso de presentar a alguien a tu círculo íntimo?",
      "¿Qué papel juega el perdón sincero en tu forma de construir vínculos duraderos?",
      "Si tuviéramos que resumir el contrato básico de nuestra convivencia ideal, ¿cuáles serían los 3 puntos principales?"
    ]
  },
  {
    "id": "citas_nivel3",
    "titulo": "Citas: Nivel 3 (Química & Conexión Profunda)",
    "descripcion": "Para citas avanzadas, parejas o momentos de máxima confianza.",
    "icono": "❤️",
    "color": "#ec4899",
    "badge": "Intenso",
    "preguntas": [
      "¿Qué es algo que casi nadie sabe de ti porque te cuesta mostrarte vulnerable?",
      "¿Cuál ha sido la lección más dolorosa pero valiosa de tus relaciones anteriores?",
      "¿Cuál es tu lenguaje del amor principal (palabras de afirmación, tiempo de calidad, contacto físico, actos de servicio o regalos)?",
      "¿Qué parte de tu personalidad te da más orgullo y cuál te cuesta más aceptar?",
      "¿Qué te hace sentir profundamente conectado y atraído hacia una persona?",
      "Si pudieras pedirle un deseo al universo sobre nuestro futuro hoy, ¿qué pedirías?",
      "¿Qué es lo más cursi o romántico que has hecho (o que te gustaría que hicieran por ti)?",
      "¿Qué significa la fidelidad y la lealtad para ti en una pareja actual?",
      "¿Qué herida de la infancia sientes que todavía influye en tus relaciones adultas?",
      "¿Cuándo fue la última vez que lloraste delante de alguien y qué lo provocó?",
      "¿Qué te da más miedo: que te rechacen o que te conozcan tan bien que descubran tus fallas?",
      "¿Qué detalle de mi comportamiento o forma de ser te llamó la atención hoy?",
      "¿Cuál es tu mayor fantasía romántica o emocional que aún no has cumplido?",
      "Si hoy fuera el último día que pudiéramos hablar, ¿qué te gustaría decirme?",
      "¿Qué significa para ti el éxito en la vida más allá del dinero y lo profesional?",
      "¿Cómo sabes con certeza cuándo estás realmente enamorado/a de alguien?",
      "¿Qué sacrificio estarías dispuesto a hacer por amor y cuál jamás harías?",
      "¿Cuál es tu mayor miedo respecto a envejecer?",
      "¿Qué parte de tu cuerpo o de tu mente te ha costado más aprender a querer?",
      "¿Cuál ha sido el momento en que te has sentido más solo/a en tu vida?",
      "¿Qué te hace sentir completamente en paz y seguro al lado de alguien?",
      "Si pudieras pedir perdón sinceramente a una persona de tu pasado, ¿a quién sería y por qué?",
      "¿Qué concepto de amor aprendiste de tus padres que decidiste no repetir?",
      "¿Cuál es una caricia o gesto de afecto que te desarma por completo?",
      "¿Qué estás buscando construir en los próximos 5 años que le dé sentido a todo?",
      "¿Qué es lo que más te asusta de entregarte por completo a una nueva relación?",
      "Si pudieras revivir un solo día perfecto de tu vida, ¿cuál elegirías?",
      "¿Cuál es esa cualidad que admiras profundamente en los demás y que sientes que a ti te falta?",
      "¿Qué canción o melodía sientes que describe exactamente tu alma?",
      "¿Cómo te gustaría ser recordado por las personas que más te quisieron cuando ya no estés?",
      "¿Qué es algo que hiciste en el pasado por lo que todavía te cuesta perdonarte a ti mismo?",
      "¿Qué significa para ti sentirte amado de verdad en un día común y corriente?",
      "¿Cuál ha sido el momento más vulnerable que has compartido con otra persona?",
      "¿Qué es lo primero que pensaste sobre mí cuando nos vimos por primera vez?",
      "Si supieras que te quedan exactamente 6 meses de vida, ¿qué cambiarías inmediatamente hoy?",
      "¿Qué parte de tu historia personal sientes que la mayoría de la gente juzga sin entender?",
      "¿Qué te hace sentir que una persona vale la pena a pesar de las dificultades del camino?",
      "¿Cuál ha sido el abrazo o mirada más sanadora que has recibido en tu vida?",
      "¿Qué es algo que anhelas escuchar de la persona que amas cuando estás pasando por un mal día?",
      "¿Cómo sabes cuándo has conectado espiritualmente o emocionalmente con alguien más allá de la piel?",
      "¿Qué vacío o anhelo interior sientes que ninguna persona externa puede llenar excepto tú?",
      "¿Cuál ha sido tu mayor acto de valentía emocional en una relación?",
      "¿Qué sueño secreto guardas en tu corazón que casi nunca te atreves a decir en voz alta por miedo al ridículo?",
      "¿Cómo se siente en tu cuerpo cuando experimentas verdadera paz al lado de alguien?",
      "¿Qué es lo más hermoso que alguien ha dicho sobre tu corazón o tu forma de ser?",
      "¿Qué herida sientes que ya cicatrizó por completo y te convirtió en alguien más sabio?",
      "¿Qué significa para ti envejecer juntos y ver cambiar el cuerpo de la persona que amas?",
      "¿Qué te hace sentir profundamente admirado/a y respetado/a en pareja?",
      "Si pudieras sanar un solo recuerdo triste de tu infancia, ¿cuál borrarías de tu memoria?",
      "¿Qué es lo que más agradeces de la persona que eres hoy frente al espejo?",
      "¿Cómo sabes cuando alguien te está mirando con amor genuino y no solo con deseo?",
      "¿Qué parte de tu rutina diaria disfrutas más compartir en silencio con alguien?",
      "¿Qué crees que pasa con el amor cuando las mariposas del comienzo se transforman en complicidad madura?",
      "¿Cuál ha sido la despedida más desgarradora que te ha tocado vivir?",
      "¿Qué promesa te hiciste a ti mismo/a sobre no volver a permitir en tu vida afectiva?",
      "¿Qué es algo que sientes que te hace único/a a la hora de amar y cuidar a los demás?",
      "¿Cómo te gustaría que manejemos los momentos en que la rutina o el cansancio nos alejen?",
      "¿Qué te despierta ternura infinita en los gestos cotidianos de alguien?",
      "Si tuvieras que escribirle una carta a tu corazón cansado, ¿qué palabras de aliento le dirías?",
      "¿Qué lección sobre la paciencia te ha enseñado la vida de forma dura?",
      "¿Qué significa para ti que alguien sea tu refugio seguro en medio de una tormenta?",
      "¿Cuál es el recuerdo más cálido que tienes de sentirte protegido/a por alguien?",
      "¿Qué detalle íntimo sobre tu forma de sentir te da miedo que sea 'demasiado intenso' para otros?",
      "¿Qué te hace sentir que puedes desnudarte el alma sin miedo al juicio?",
      "¿Qué papel juega la complicidad y las risas cómplices en tu idea del amor duradero?",
      "¿Cómo te das cuenta de que has comenzado a confiar verdaderamente en alguien?",
      "¿Qué herida emocional del pasado sentías que era mortal y con el tiempo descubriste que te hizo invencible?",
      "¿Qué estás dispuesto/a a aprender de mí que pueda desafiar tu forma de ver el mundo?",
      "¿Cuál ha sido el acto de perdón más difícil pero liberador que has concedido en tu vida?",
      "¿Qué te hace sentir que una conversación valió cada segundo de tu tiempo?",
      "Si pudieras detener el tiempo por 5 minutos ahora mismo, ¿qué te gustaría hacer o decir?",
      "¿Qué emoción te cuesta más procesar: la tristeza, la rabia, la culpa o la impotencia?",
      "¿Cómo te gustaría que celebremos nuestros logros personales cuando estemos juntos?",
      "¿Qué cualidad mía sientes que podría complementar tus mayores debilidades?",
      "¿Qué significa para ti la libertad dentro de un compromiso de pareja?",
      "¿Cuál es la conversación más honesta que has tenido contigo mismo/a en el último año?",
      "¿Qué te hace sentir que estás en casa cuando estás con una persona específica?",
      "¿Qué huella te gustaría dejar en el corazón de quienes compartan la vida contigo?",
      "¿Cuál ha sido la mayor muestra de amor incondicional que has presenciado en tu vida?",
      "¿Qué te hace sentir orgulloso/a de la forma en que has aprendido a amar con los años?",
      "¿Cómo describirías la mirada de alguien que te conoce y te acepta exactamente tal como eres?",
      "¿Qué parte de tu futuro te llena de más ilusión cuando imaginas una vida compartida?",
      "¿Qué lección sobre soltar y dejar ir te costó más lágrimas aprender?",
      "¿Qué te hace sentir que no estás solo/a en este universo caótico?",
      "¿Cuál es esa verdad sobre ti que antes escondías y hoy abrazas con orgullo?",
      "¿Qué pequeño gesto cotidiano te hace sentir profundamente valorado/a por tu pareja?",
      "¿Cómo te gustaría que resolvamos nuestras diferencias cuando ambos estemos cansados y vulnerables?",
      "¿Qué significa para ti tener fe en el amor después de haber sufrido decepciones?",
      "¿Qué es lo más generoso que has hecho por alguien sin esperar nada a cambio?",
      "¿Cómo sabes cuando una persona ha dejado de ser un conocido para convertirse en alguien irremplazable?",
      "¿Qué mensaje de gratitud le darías hoy a las personas que te rompieron el corazón por haberte enseñado tanto?",
      "¿Qué parte de tu ternura sientes que el mundo contemporáneo a veces no sabe apreciar?",
      "¿Cómo te gustaría que cuidemos nuestra chispa y nuestra intimidad con el paso de los años?",
      "¿Qué es lo más auténtico que has descubierto sobre quién eres en soledad?",
      "¿Qué te hace sentir que vale la pena arriesgarse a amar de nuevo aunque dé miedo?",
      "Si pudieras leer en una bola de cristal cómo termina esta historia, ¿preferirías leerla o vivirla paso a paso?",
      "¿Qué palabra define mejor lo que necesitas de una pareja en este preciso momento de tu vida?",
      "¿Cómo te gustaría que te abracen cuando no tengas fuerzas para explicar qué te pasa?",
      "¿Qué es lo que más te conmueve de la fragilidad humana?",
      "Si tuvieras que agradecerle a este instante presente una sola cosa, ¿qué agradecerías?"
    ]
  },
  {
    "id": "amigos_fiesta",
    "titulo": "Amigos & Fiesta (Modo Carrete)",
    "descripcion": "Confidencias, anécdotas locas y momentos de trágame tierra con el grupo.",
    "icono": "🍻",
    "color": "#a855f7",
    "badge": "Fiesta",
    "preguntas": [
      "¿Cuál ha sido la peor borrachera o anécdota fiestera que aún te recuerdan?",
      "¿A quién de este grupo llamarías a las 3:00 AM para que te saque de un apuro?",
      "¿Cuál es la mentira más piadosa (o descarada) que le has dicho a alguien presente?",
      "¿Qué fue lo más ilegal o al borde de la ley que hiciste de adolescente?",
      "¿Quién en este grupo tiene más cara de que terminará siendo famoso o arrestado?",
      "¿Cuál ha sido el mensaje que enviaste al chat equivocado y casi te cuesta la vida?",
      "¿Qué es algo vergonzoso en tu historial de búsqueda de internet si lo revisamos ya?",
      "¿Alguna vez te gustó o te sentiste atraído por la pareja de un amigo/a?",
      "¿Qué es lo más asqueroso que has comido o bebido por perder una apuesta?",
      "¿Cuál ha sido el peor corte de pelo o look que tuviste en tu vida?",
      "¿Alguna vez te colaste en una fiesta o evento exclusivo sin invitación?",
      "¿Quién de los presentes es el peor copiloto o conductor del mundo?",
      "¿Qué secreto tonto le ocultaste a tus papás durante años y se enteraron hace poco?",
      "¿Cuál fue la multa o llamada de atención más ridícula que has recibido?",
      "¿Qué es lo más extraño que has encontrado en la casa de un amigo?",
      "¿Cuál ha sido la pelea o discusión más absurda que tuviste con un amigo?",
      "¿Quién del grupo tardaría menos de 24 horas en gastarse una herencia millonaria?",
      "¿Cuál ha sido la anécdota en que casi terminas preso o perseguido por la policía?",
      "¿Qué apodo vergonzoso tenías en el colegio y por qué te lo pusieron?",
      "¿Has roto algo muy caro en una casa ajena y te hiciste el desentendido?",
      "¿Cuál ha sido tu peor experiencia con fuegos artificiales o bromas pesadas?",
      "¿Quién de nosotros crees que sería el primero en morir en una película de terror?",
      "¿Qué canción te sabes de memoria completa de principio a fin sin fallar una sola letra?",
      "¿Alguna vez te quedaste dormido en un lugar insólito (paradero, baño, discoteca)?",
      "¿Cuál ha sido la compra online que hiciste estando borracho y te llegó días después?",
      "¿Quién tiene las peores historias de citas del grupo?",
      "¿Cuál ha sido tu mayor estafa o momento en que te vieron la cara de tonto?",
      "¿Qué es lo peor que has vomitado o te ha tocado limpiar en una fiesta?",
      "¿Quién de aquí es el que más se transforma cuando toma dos tragos de más?",
      "Si tuviéramos que ir a un reality show juntos, ¿cuál de nosotros ganaría por estratega?",
      "¿Cuál es el trago o licor que tienes prohibido tomar porque te borra la memoria?",
      "¿Alguna vez fingiste estar enfermo para no ir a un cumpleaños o junta aburrida?",
      "¿Qué es lo más patético que has hecho por llamar la atención de alguien que te gustaba?",
      "¿Quién de este grupo sería el peor compañero de celda en una cárcel?",
      "¿Cuál ha sido el peor regalo del 'Amigo Secreto' que has recibido en tu vida?",
      "¿Alguna vez te fuiste de un local o restaurante sin pagar la cuenta (perro muerto)?",
      "¿Quién del grupo es el más probable que arme una escena de celos en público?",
      "¿Cuál ha sido la broma telefónica o por chat más pesada que hiciste?",
      "Si todos tuviéramos que sobrevivir en una isla desierta, ¿a quién nos comeríamos primero?",
      "¿Qué es algo que todos juraron mantener en secreto de una fiesta y hoy ya se puede contar?",
      "¿Quién de aquí es el que peor aguanta el picante en la comida?",
      "¿Cuál ha sido la caída más ridícula y aparatosa que tuviste en la calle?",
      "¿Alguna vez te pusiste la ropa al revés o con la etiqueta gigante para afuera todo el día sin darte cuenta?",
      "¿Quién es el más probable que termine bailando arriba de la mesa a las 4:00 AM?",
      "¿Cuál ha sido la peor excusa que inventaste para salirte de un grupo de WhatsApp?",
      "¿Quién es el más tacaño a la hora de dividir la cuenta en el restaurante?",
      "¿Alguna vez te pillaron cantando o bailando frente al espejo creyendo que estabas solo?",
      "¿Cuál ha sido la experiencia paranormal o de miedo que viviste con amigos?",
      "¿Quién de nosotros tiene el gusto musical más culposo y cuestionable de todos?",
      "¿Qué es lo más ridículo que hiciste para no encontrarte de frente con alguien en el supermercado o la calle?",
      "¿Quién es el más probable que pierda el carnet o la billetera en una sola salida?",
      "¿Alguna vez te disfrazaste de algo tan malo que nadie entendía de qué ibas en Halloween?",
      "¿Cuál ha sido la peor conversación que tuviste con un taxista o conductor de Uber?",
      "¿Quién de este grupo tiene más cara de que se volvería líder de una secta?",
      "¿Alguna vez te comiste la comida de tu compañero de departamento o hermano y le echaste la culpa al perro?",
      "¿Cuál ha sido la resaca más infernal que duró dos días seguidos?",
      "¿Quién de aquí es el más impuntual crónico que te hace esperar 45 minutos?",
      "¿Qué es lo más vergonzoso que gritaste en un estadio o recital?",
      "¿Alguna vez te rompiste un hueso por hacer una estupidez digna de Jackass?",
      "¿Quién de nosotros se enamora más rápido de la persona equivocada?",
      "¿Cuál ha sido el peor chisme en el que te viste involucrado sin tener nada que ver?",
      "¿Quién es el que más fotos se saca antes de elegir una sola para subir a Instagram?",
      "¿Alguna vez vomitaste por la ventana de un auto en movimiento?",
      "¿Quién es el más probable que se agarre a combos con alguien en una discoteca?",
      "¿Qué es lo más vergonzoso que tus papás le han contado a tus amigos sobre ti?",
      "¿Quién de aquí ronca tan fuerte que no deja dormir a nadie en los paseos de fin de semana?",
      "¿Alguna vez te quedaste encerrado en el baño de un bar o restaurante y tuviste que pedir auxilio?",
      "¿Quién del grupo es el que mejor miente cuando la situación se pone difícil?",
      "¿Cuál ha sido la peor equivocación de nombre que tuviste saludando a alguien?",
      "¿Quién es el más probable que termine viviendo en una furgoneta hippie vendiendo pulseras?",
      "¿Alguna vez te caíste adentro de una piscina con ropa, zapatos y celular en el bolsillo?",
      "¿Quién del grupo tiene el armario o la pieza más desordenada y caótica del mundo?",
      "¿Cuál ha sido la apuesta más absurda que ganaste y qué premio te dieron?",
      "¿Quién es el que más se hace rogar para salir de fiesta y después es el último en irse?",
      "¿Alguna vez usaste el cepillo de dientes de otra persona sin pedirle permiso?",
      "¿Quién de nosotros sería el peor espía de la historia porque confiesa todo en 5 minutos?",
      "¿Cuál ha sido el piropo más ordinario o ridículo que te han gritado en la calle?",
      "¿Quién del grupo es el rey de los memes en el chat colectivo?",
      "¿Alguna vez te quedaste sin papel higiénico en un baño ajeno y tuviste que improvisar?",
      "¿Quién de aquí es el más hipocondríaco que se busca síntomas en Google y ya se siente en las últimas?",
      "¿Cuál ha sido la fiesta clandestina o evento más turbio al que fuiste?",
      "¿Quién es el que tiene más anécdotas con exparejas tóxicas para escribir un libro entero?",
      "¿Alguna vez te pusiste a llorar de borracho/a por una tontera absoluta?",
      "¿Quién del grupo sería el primero en arruinar una sorpresa porque no sabe guardar secretos?",
      "¿Cuál ha sido el peor olor que te ha tocado soportar en una junta de amigos?",
      "¿Quién de nosotros es el más competitivo jugando beer pong o cartas?",
      "¿Alguna vez te pillaron haciendo algo tan ridículo que fingiste que era un experimento social?",
      "¿Quién es el que más se pierde cuando van a una ciudad o festival desconocido?",
      "¿Cuál ha sido la foto más humillante que tus amigos tienen guardada en su celular para tu cumpleaños?",
      "Si tuviéramos que elegir a uno de este grupo para que nos defienda en un juicio como abogado improvisado, ¿a quién elegimos?",
      "¿Quién es el más probable que se case en Las Vegas con alguien que conoció hace 3 días?",
      "¿Alguna vez mandaste un meme burlándote de alguien al mismo chat grupal donde esa persona estaba?",
      "¿Quién de aquí tiene la risa más escandalosa y contagiosa que se escucha a dos cuadras?",
      "¿Cuál ha sido la peor mezcla de alcoholes que tomaste y juraste jamás volver a repetir?",
      "¿Quién es el más probable que se haga amigo de los perros de la fiesta en vez de hablar con la gente?",
      "¿Alguna vez te fuiste de una cita escapándote por el baño del local?",
      "¿Quién de nosotros sería el más inútil en un escape room?",
      "¿Cuál ha sido la anécdota de vacaciones de amigos que todavía nos hace reír con lágrimas?",
      "¿Quién del grupo tiene más corazón de abuelo/a que a las 11:00 PM ya está bostezando?",
      "Si tuviéramos que describir a este grupo de amigos con el título de una película de comedia, ¿cuál sería?"
    ]
  },
  {
    "id": "empresas_trabajo",
    "titulo": "Empresas & Trabajo (Team Building)",
    "descripcion": "Dinámicas constructivas, romper la formalidad y conocer al equipo humano.",
    "icono": "💼",
    "color": "#10b981",
    "badge": "Empresas",
    "preguntas": [
      "¿Cuál fue tu primer trabajo oficial y qué fue lo más raro que te tocó hacer?",
      "Si tuvieras un 'superpoder' en la oficina, ¿cuál te salvaría el día?",
      "¿Qué es lo que más valoras en un colega de trabajo en momentos de alta presión?",
      "Si pudieras eliminar una sola reunión o proceso burocrático de tu semana, ¿cuál sería?",
      "¿Qué talento oculto tienes que nadie en el equipo se imagina?",
      "¿Cuál ha sido el mejor cumplido o reconocimiento profesional que has recibido?",
      "Si tuvieras presupuesto ilimitado para una actividad de integración del equipo, ¿qué haríamos?",
      "¿Qué consejo le darías a tu yo del pasado en su primer día laboral?",
      "¿Qué sonido de notificación (Slack, Teams, correo) te produce un micro-infarto?",
      "¿Cuál ha sido tu mayor metedura de pata en una llamada de Zoom o Teams (micrófono abierto)?",
      "Si pudieras intercambiar puesto de trabajo con alguien de la empresa por un día, ¿con quién sería?",
      "¿Qué es lo que más te motiva a levantarte los lunes por la mañana?",
      "¿Cómo desconectas verdaderamente del trabajo cuando termina tu jornada laboral?",
      "¿Qué curso, habilidad o disciplina te gustaría aprender con financiamiento de la empresa?",
      "¿Cuál ha sido el cliente o proyecto más desafiante que has tenido y cómo saliste adelante?",
      "Si la empresa fuera una tripulación espacial, ¿cuál sería tu rol dentro de la nave?",
      "¿Qué snack o bebida no puede faltar jamás en tu escritorio?",
      "¿Qué costumbre corporativa tradicional consideras que debería desaparecer para siempre?",
      "¿Cuál ha sido la mejor victoria que celebramos juntos como equipo recientemente?",
      "¿Qué cualidad de liderazgo admiras más en un jefe o mentor?",
      "¿Prefieres home office 100%, híbrido o te gusta la energía de la oficina?",
      "¿Qué playlist o tipo de música escuchas para concentrarte a fondo?",
      "Si pudieras inventar un feriado nacional nuevo, ¿qué se celebraría ese día?",
      "¿Qué proyecto laboral te ha llenado de más orgullo hasta el día de hoy?",
      "¿Cómo podemos mejorar la comunicación entre nosotros en los momentos difíciles?",
      "¿Qué es algo que aprendiste a las malas en tu primer año de vida laboral?",
      "Si el equipo tuviera que fundar una startup juntos mañana, ¿qué producto o servicio venderíamos?",
      "¿Cuál ha sido el peor trabajo temporal que tuviste en vacaciones de verano?",
      "¿Qué harías si un día te dan 1 hora libre obligatoria dentro del horario de trabajo para hacer lo que quieras?",
      "¿Qué colega del equipo te ha sacado de un apuro laboral de forma más heroica?",
      "¿Qué frase cliché de oficina (ej: 'revisemos esto offline', 'pongámonos la camiseta') no soportas más?",
      "Si pudieras decorar la oficina entera con una temática ridícula, ¿cuál elegirías?",
      "¿Cuál es el mejor truco de productividad o teclado que usas a diario y todos deberían conocer?",
      "¿Qué objetivo personal o profesional quieres lograr antes de que termine este año?",
      "Si tuviéramos que elegir una mascota oficial para el equipo, ¿qué animal nos representaría?",
      "¿Qué es lo más divertido que has presenciado en una fiesta de fin de año de la empresa?",
      "¿Cómo manejas el síndrome del impostor cuando te asignan una responsabilidad gigante?",
      "¿Qué cambiarías de tu rutina matutina antes de empezar a trabajar para ser más feliz?",
      "¿Cuál ha sido el correo electrónico que tardaste 40 minutos en redactar con miedo a enviarlo?",
      "Si pudieras automatizar con inteligencia artificial una sola tarea repetitiva de tu día, ¿cuál sería?",
      "¿Qué es algo que tus colegas hacen que te alegra el día de trabajo al instante?",
      "¿Cuál es tu lugar favorito cerca de la oficina para almorzar o tomarse un café de escape?",
      "Si pudieras redefinir el horario laboral semanal, ¿cómo organizarías tus horas?",
      "¿Qué habilidad blanda (empatía, negociación, paciencia) sientes que has desarrollado más en este trabajo?",
      "¿Cuál ha sido la presentación en vivo o pitch más estresante que te ha tocado dar?",
      "¿Qué objeto curioso tienes en tu escritorio que tiene un significado especial para ti?",
      "¿Cómo reaccionas cuando se cae el servidor o internet justo antes de una entrega importante?",
      "¿Qué consejo le darías a alguien que recién se incorpora hoy a nuestro equipo?",
      "Si tuvieras que explicarle tu trabajo a un niño de 6 años en una sola frase, ¿qué le dirías?",
      "¿Cuál es el mito más falso que la gente de afuera tiene sobre lo que hacemos en nuestra área?",
      "¿Qué colega consideras que es el más empático y comprensivo cuando alguien tiene un problema?",
      "¿Cuál ha sido la llamada con un cliente o proveedor más surrealista que has tenido?",
      "Si pudiéramos tener una máquina expendedora gratuita en la oficina, ¿de qué la llenarías?",
      "¿Qué aprendizaje valioso te dejó tu peor error laboral?",
      "¿Cómo gestionas la sobrecarga de correos sin responder después de volver de vacaciones?",
      "¿Qué beneficio laboral no tradicional (gimnasio, días libres por cumpleaños, snacks) valoras más?",
      "Si tuvieras que escribir un libro sobre nuestro equipo, ¿qué título le pondrías?",
      "¿Qué hábito has implementado para no mirar los mensajes del trabajo en fines de semana?",
      "¿Cuál ha sido la reunión que claramente pudo haber sido un correo de 2 líneas?",
      "¿Qué superpoder de organización (calendario, libretas, Notion, Trello) es tu religión diaria?",
      "Si pudiéramos hacer un voluntariado social juntos como empresa, ¿a qué causa te gustaría apoyar?",
      "¿Qué es lo más creativo que has tenido que inventar para solucionar un problema urgente?",
      "¿Cómo te gustaría que celebremos cuando cerremos con éxito el próximo gran hito del equipo?",
      "¿Qué colega del equipo crees que tiene madera de CEO o futuro director de empresa?",
      "¿Qué es lo que más te sorprendió para bien cuando entraste a trabajar a esta organización?",
      "Si tuvieras que armar un meme sobre un día típico de nuestra área, ¿qué imagen usarías?",
      "¿Cómo manejas las diferencias de opinión técnica con un compañero de tu mismo nivel?",
      "¿Qué charla TED o libro de negocios te ha inspirado genuinamente en tu carrera?",
      "¿Qué pequeño ritual haces al cerrar la laptop o apagar el computador para marcar el fin del día?",
      "¿Cuál es la pregunta más extraña que te han hecho en una entrevista de trabajo?",
      "Si pudieras agregar una sala de juegos o descanso a la oficina, ¿qué pondrías adentro?",
      "¿Qué persona del equipo consideras que mantiene la calma olímpica bajo fuego cruzado?",
      "¿Cómo ha evolucionado tu estilo de trabajo desde tus inicios profesionales hasta hoy?",
      "¿Qué es algo que nadie te enseñó en la universidad o instituto y tuviste que aprender a pulso?",
      "Si la empresa te financiara 1 mes sabático para investigar una idea innovadora, ¿qué investigarías?",
      "¿Qué opinas sobre las reuniones de pie (standups) de 15 minutos: útiles o agotadoras?",
      "¿Cuál ha sido el mejor feedback que te ha ayudado a corregir el rumbo profesional?",
      "¿Qué colega tiene siempre la respuesta indicada cuando no encuentras un archivo o proceso?",
      "Si pudiéramos hacer una sesión de trabajo al aire libre en un parque un viernes, ¿te sumarías?",
      "¿Cómo podemos fomentar más la creatividad y menos el miedo a equivocarse en nuestros proyectos?",
      "¿Qué detalle de la cultura de nuestro equipo no cambiarías por nada del mundo?",
      "¿Cuál ha sido la negociación más dura en la que has participado?",
      "Si tuvieras que definir el propósito central de lo que hacemos en el equipo, ¿cuál es su impacto real?",
      "¿Qué hábito de concentración extrema te funciona cuando tienes que sacar un informe urgente?",
      "¿Cómo te gusta que te reconozcan un buen trabajo: en público, en privado o con incentivo concreto?",
      "¿Qué herramienta digital nueva descubriste este año que te cambió la vida laboral?",
      "Si el equipo hiciera un intercambio de roles por un día entero, ¿qué puesto te gustaría probar?",
      "¿Cuál es el mejor recuerdo que tienes de un almuerzo o after-office compartido con este equipo?",
      "¿Qué valor humano consideras que nunca debe perderse en el mundo corporativo actual?",
      "Si tuvieras que agradecerle a un compañero presente por algo concreto que hizo por ti, ¿a quién le agradecerías hoy?",
      "¿Qué consejo le darías a un colega que está sintiendo los primeros síntomas de agotamiento o burnout?",
      "¿Cuál ha sido la anécdota más divertida o curiosa que te ha tocado vivir en un viaje o evento de trabajo?",
      "¿Qué cambio simple en el espacio físico o virtual de trabajo aumentaría tu bienestar diario?",
      "¿Qué es lo que más te desconcentra durante el día y cómo logras recuperar el foco?",
      "Si pudiéramos instaurar un 'viernes temático' al mes en el equipo, ¿qué temática propondrías?",
      "¿Qué habilidad técnica te ha resultado más difícil pero más gratificante de dominar en tu carrera?",
      "¿Cómo te gusta organizar tus pendientes diarios: lista en papel, apps digitales o en la cabeza?",
      "¿Qué aprendizaje de liderazgo rescatas del mejor jefe o mentor que has tenido en tu vida?",
      "¿Cuál es tu café, té o infusión predilecta para sobrevivir a las tardes de alta exigencia?",
      "Si tuviéramos que elegir un lema o frase inspiradora para nuestro equipo este año, ¿cuál propondrías?"
    ]
  },
  {
    "id": "quien_es_mas_probable",
    "titulo": "¿Quién es Más Probable Que...?",
    "descripcion": "A la de tres, todos apuntan con el dedo a un participante.",
    "icono": "👉",
    "color": "#6366f1",
    "badge": "Rápido",
    "preguntas": [
      "¿Quién es más probable que termine viviendo en otro país de la nada?",
      "¿Quién es más probable que sobreviva a un apocalipsis zombie por pura astucia?",
      "¿Quién es más probable que se gaste todo el sueldo el primer día en tonteras?",
      "¿Quién es más probable que llore viendo una película de dibujos animados?",
      "¿Quién es más probable que se quede dormido en una reunión importante?",
      "¿Quién es más probable que sea el primero en iniciar una conversación con un extraño?",
      "¿Quién es más probable que pierda las llaves o el celular dos veces en una noche?",
      "¿Quién es más probable que se enamore de su mejor amigo/a?",
      "¿Quién es más probable que termine en el escenario cantando karaoke desafinado?",
      "¿Quién es más probable que se una a una secta sin darse cuenta?",
      "¿Quién es más probable que olvide el cumpleaños de su propia pareja?",
      "¿Quién es más probable que envíe un screenshot de un chat a la misma persona de quien está hablando?",
      "¿Quién es más probable que adopte un quinto perro o gato de la calle?",
      "¿Quién es más probable que gane un millón de dólares en la lotería y lo pierda todo en un año?",
      "¿Quién es más probable que se pierda usando Google Maps a dos cuadras de su casa?",
      "¿Quién es más probable que arme un escándalo público si le traen el pedido equivocado?",
      "¿Quién es más probable que sea descubierto hablando solo por la calle?",
      "¿Quién es más probable que sea el primero en bailar en una fiesta vacía?",
      "¿Quién es más probable que tenga una cuenta de TikTok secreta con millones de visitas?",
      "¿Quién es más probable que se haga un tatuaje del que se arrepentirá a los dos días?",
      "¿Quién es más probable que termine siendo presidente o político corrupto?",
      "¿Quién es más probable que sobreviva en una isla desierta?",
      "¿Quién es más probable que finja su propia muerte para evitar pagar una deuda tonta?",
      "¿Quién es más probable que se tropiece y se caiga en las escaleras mecánicas del mall?",
      "¿Quién es más probable que se sepa de memoria todos los chismes de los famosos?",
      "¿Quién es más probable que se quede encerrado en un baño público?",
      "¿Quién es más probable que le dé 'me gusta' por error a una foto de su ex de hace 6 años?",
      "¿Quién es más probable que empiece una pelea con un desconocido en el tráfico?",
      "¿Quién es más probable que termine siendo millonario por una idea absurda?",
      "¿Quién es más probable que se coma la comida que se le cayó al piso aplicando la regla de los 5 segundos?",
      "¿Quién es más probable que se haga amigo del guardia o del barman en la fiesta?",
      "¿Quién es más probable que gaste dinero en un curso milagroso para volverse rico en internet?",
      "¿Quién es más probable que termine en urgencias por un reto tonto en una fiesta?",
      "¿Quién es más probable que se presente en pijama al trabajo o a la universidad?",
      "¿Quién es más probable que se quede viendo videos en TikTok hasta las 5:00 AM un día de semana?",
      "¿Quién es más probable que aparezca en un video viral de internet sin saberlo?",
      "¿Quién es más probable que se coma el postre de otra persona en el refrigerador y lo niegue a muerte?",
      "¿Quién es más probable que se olvide de dónde dejó estacionado el auto en el centro comercial?",
      "¿Quién es más probable que termine de novio/a con alguien que conoció en una sala de espera?",
      "¿Quién es más probable que empiece una dieta estricta un lunes y la rompa el martes a la hora de almuerzo?",
      "¿Quién es más probable que se asuste con su propia sombra en un pasillo oscuro?",
      "¿Quién es más probable que le crea una mentira absurda dicha con total seriedad?",
      "¿Quién es más probable que arme una maleta gigante de 30 kilos para un viaje de fin de semana de dos días?",
      "¿Quién es más probable que se invente una excusa insólita para no ir a un evento social?",
      "¿Quién es más probable que llore de emoción al probar una comida deliciosa?",
      "¿Quién es más probable que se gaste los ahorros del mes en entradas para un concierto?",
      "¿Quién es más probable que se quede dormido en el cine a los 15 minutos de empezar la película?",
      "¿Quién es más probable que se haga amigo de toda la mesa del lado en un restaurante?",
      "¿Quién es más probable que le hable a las plantas para que crezcan más rápido?",
      "¿Quién es más probable que finja hablar por teléfono para evitar saludar a un conocido incómodo?",
      "¿Quién es más probable que tenga más de 50 pestañas abiertas en el navegador del celular?",
      "¿Quién es más probable que sea abducido por extraterrestres y vuelva convencido de que son buena onda?",
      "¿Quién es más probable que arme un debate filosófico profundo en medio de una fiesta ruidosa?",
      "¿Quién es más probable que compre algo solo porque el empaque era bonito aunque no le sirva de nada?",
      "¿Quién es más probable que se suba a la micro o al metro equivocado por ir mirando el celular?",
      "¿Quién es más probable que se coma una pizza familiar entera en una sola sentada?",
      "¿Quién es más probable que se haga viral por una caída vergonzosa?",
      "¿Quién es más probable que le dé una propina gigantesca al mozo solo porque le cayó bien?",
      "¿Quién es más probable que se sepa de memoria los signos zodiacales de todo el grupo?",
      "¿Quién es más probable que termine como ermitaño viviendo en una cabaña en el bosque sin internet?",
      "¿Quién es más probable que tenga 30 alarmas puestas con 5 minutos de diferencia para poder despertar?",
      "¿Quién es más probable que se ponga a limpiar y ordenar compulsivamente la casa de un amigo?",
      "¿Quién es más probable que mande un meme en medio de una discusión seria en el chat familiar?",
      "¿Quién es más probable que se gaste la quincena comprando ropa que nunca va a usar?",
      "¿Quién es más probable que se tropiece caminando por una superficie completamente plana?",
      "¿Quién es más probable que se aprenda una coreografía entera de K-pop o TikTok para una fiesta?",
      "¿Quién es más probable que se meta a nadar al mar con agua helada mientras todos tiritan en la orilla?",
      "¿Quién es más probable que guarde cajas de zapatos vacías 'por si acaso sirven para algo'?",
      "¿Quién es más probable que termine arrestado por entrar a una propiedad privada buscando una buena foto?",
      "¿Quién es más probable que se coma el último pedazo de torta sin preguntarle a nadie en la casa?",
      "¿Quién es más probable que sea el primero en empezar a llorar en una boda aunque apenas conozca a los novios?",
      "¿Quién es más probable que se invente un emprendimiento loco y termine haciéndolo funcionar?",
      "¿Quién es más probable que se ponga a cantar villancicos navideños en pleno mes de julio?",
      "¿Quién es más probable que pierda una discusión porque le dio un ataque de risa incontrolable?",
      "¿Quién es más probable que se compre una bicicleta profesional y la use solo dos veces?",
      "¿Quién es más probable que le dé consejos de amor a todos sus amigos teniendo su propia vida sentimental en llamas?",
      "¿Quién es más probable que tenga una playlist secreta de reggaetón antiguo que escucha a escondidas?",
      "¿Quién es más probable que se coma una fruta con cáscara por pereza de pelarla?",
      "¿Quién es más probable que se meta a un reality show de cocina sin saber cocinar ni un huevo frito?",
      "¿Quién es más probable que arme un escándalo divertido si ve una araña en la pared?",
      "¿Quién es más probable que se aprenda de memoria los diálogos completos de Shrek?",
      "¿Quién es más probable que se ponga a ordenar las papas fritas por tamaño antes de comérselas?",
      "¿Quién es más probable que se compre un juego de mesa de 4 horas de duración y obligue a todos a jugarlo?",
      "¿Quién es más probable que sea el primero en proponer pedir bajón a las 3:30 AM?",
      "¿Quién es más probable que se quede sin saldo o batería en el peor momento de la noche?",
      "¿Quién es más probable que le ponga nombres de personas humanas a sus autos o computadores?",
      "¿Quién es más probable que termine como influencer famoso de cosas totalmente absurdas?",
      "¿Quién es más probable que se ponga a bailar salsa o cumbia con una tía en un matrimonio?",
      "¿Quién es más probable que intente arreglar algo de electricidad en su casa y termine cortando la luz de toda la cuadra?",
      "¿Quién es más probable que tenga guardados screenshots de conversaciones comprometedoras de hace 5 años?",
      "¿Quién es más probable que se meta a nadar a una fuente pública en una plaza después de una fiesta?",
      "¿Quién es más probable que se gaste todo el dinero en juguetes para su mascota mientras come fideos con atún?",
      "¿Quién es más probable que se equivoque de fecha de cumpleaños de sus propios hermanos?",
      "¿Quién es más probable que arme una escena dramática de telenovela solo para reírse de las reacciones?",
      "¿Quién es más probable que sobreviva en la selva amazónica gracias a tutoriales de YouTube que vio de madrugada?",
      "¿Quién es más probable que se aprenda la carta completa del restaurante antes de que llegue el mesero?",
      "¿Quién es más probable que termine siendo la persona más querida por los suegros en el primer almuerzo familiar?",
      "¿Quién es más probable que se gaste una fortuna en merchandising oficial de su serie favorita?",
      "¿Quién es más probable que nos saque de un apuro en una comisaría con pura labia y carisma?",
      "¿Quién es más probable que sea el alma de la fiesta hasta los 90 años bailando con bastón?"
    ]
  }
];
